In [2]:
import pandas as pd
import numpy as np
import requests

In [67]:
# 16만개 데이터를 sampling한 데이터프레임
sampled_df = pd.read_csv('./csv/sampled_df.csv', dtype={'code':str}, index_col=0)
sampled_df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx
50639,2018-04-18,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108
87611,2016-05-23,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646
113571,2014-07-29,000270,기아차(000270),77000,buy,이윤석,SK증권,329427
32806,2019-04-03,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412
81924,2016-09-12,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416
...,...,...,...,...,...,...,...,...
151362,2011-11-14,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705
151440,2011-11-11,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587
151453,2011-11-10,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570
151630,2011-11-07,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294
151698,2011-11-04,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201

In [53]:
sampled_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21261 entries, 50639 to 151698
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   작성일     21261 non-null  object
 1   code    21261 non-null  int64
 2   제목      21261 non-null  object
 3   목표주가    21261 non-null  int64
 4   투자의견    21261 non-null  object
 5   작성자     21261 non-null  object
 6   제공출처    21261 non-null  object
 7   idx     21261 non-null  int64
dtypes: int64(3), object(5)
memory usage: 1.5+ MB

In [68]:
# 인덱스 초기화
sampled_df = sampled_df.reset_index(drop='true')
sampled_df.head()

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx
0,2018-04-18,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108
1,2016-05-23,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646
2,2014-07-29,000270,기아차(000270),77000,buy,이윤석,SK증권,329427
3,2019-04-03,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412
4,2016-09-12,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416

In [69]:
# KRX에 개별종목 시세 추이에 날짜를 넣기 위해 '-'제거한 8자리 날짜로 변환
sampled_df['작성일'] = sampled_df['작성일'].apply(lambda x: ''.join(x.split('-')))

In [70]:
sampled_df.작성일

0        20180418
1        20160523
2        20140729
3        20190403
4        20160912
           ...
21256    20111114
21257    20111111
21258    20111110
21259    20111107
21260    20111104
Name: 작성일, Length: 21261, dtype: object

In [71]:
sampled_df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx
0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108
1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646
2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427
3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412
4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416
...,...,...,...,...,...,...,...,...
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705
21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587
21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570
21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201

In [ ]:
sampled_df.to_csv('./csv/sampled_df_mod.csv', encoding='utf-8-sig')

In [132]:
df_1 = pd.read_csv('./csv/sampled_df_mod.csv', dtype={'code':str, '작성일':str} ,index_col=0)

In [17]:
df_1 = pd.read_csv('./csv/sampled_df_price10349.csv', dtype={'code':str, '작성일':str} ,index_col=0)

In [18]:
df_1['code'] = df_1['code'].apply(lambda x: x.zfill(6))

In [19]:
df_1

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,NaN,NaN
21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,NaN,NaN
21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,NaN,NaN
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [24]:
df_1['시가'] = np.nan
df_1['종가'] = np.nan

In [25]:
df_1

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,NaN,NaN
1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,NaN,NaN
2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,NaN,NaN
3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,NaN,NaN
4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,NaN,NaN
21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,NaN,NaN
21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,NaN,NaN
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [26]:
import time
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, NoSuchWindowException
from selenium import webdriver

uri = 'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020103'
options = webdriver.ChromeOptions()
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko")
driver = webdriver.Chrome(options=options)
driver.get(uri)

In [29]:
# 문제점1. 만약 없는 코드를 검색하면 이전에 검색한 결과가 그대로 출력됨
# 해결방안 -> no_search 시 크롤링하지 않게 처리
# Debugging connection was closed. Reason: Render process gone. 크롬 KRX창 Crawling 중 메모리 오류..
# 최종 crawling code
for i in df_1.index:
    try:
        input_stock = driver.find_element_by_name('tboxisuCd_finder_stkisu0_0')
        input_st_dt = driver.find_element_by_name('strtDd')
        input_ed_dt = driver.find_element_by_name('endDd')
        input_stock.clear()
        input_st_dt.clear()
        input_ed_dt.clear()
        input_stock.send_keys(df_1['code'].loc[i])
        input_st_dt.send_keys(df_1['작성일'].loc[i])
        input_ed_dt.send_keys(df_1['작성일'].loc[i])
        search_btn_1 = driver.find_element_by_id('btnisuCd_finder_stkisu0_0')
        search_btn_1.click()
        time.sleep(2.4)
        search_btn_2 = driver.find_element_by_id('jsSearchButton')
        search_btn_2.click()
        time.sleep(2.4)
        open_price = driver.find_element_by_xpath('//*[@id="jsMdiContent"]/div/div[1]/div[1]/div[1]/div[2]/div/div/table/tbody/tr/td[5]').text
        close_price = driver.find_element_by_xpath('//*[@id="jsMdiContent"]/div/div[1]/div[1]/div[1]/div[2]/div/div/table/tbody/tr/td[2]').text
        df_1['시가'].loc[i] = open_price
        df_1['종가'].loc[i] = close_price
        no_search = driver.find_element_by_xpath('//*[@id="jsGrid_div__finder_stkisu0_0"]/div/div/div[2]/div').text
        driver.find_element_by_xpath('//*[@id="jsLayer_finder_stkisu0_0"]/div[1]/button/span[1]').click()
        time.sleep(1)
        if no_search :
            df_1['시가'].loc[i] = np.nan
            df_1['종가'].loc[i] = np.nan
            time.sleep(1)
    except (NoSuchElementException, StaleElementReferenceException) as e :
        pass

KeyboardInterrupt:

In [5]:
df_1 = pd.read_csv('./csv/sampled_df_price21260.csv', dtype={'code':str, '작성일':str} ,index_col=0)

In [6]:
df_1

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,88350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,92070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,35720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,20560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,97230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
21258,20111110,210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
21259,20111107,10620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"
21260,20111104,33630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [8]:
df_1['code'] = df_1['code'].apply(lambda x : x.zfill(6))

In [9]:
df_1

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [10]:
# nan값인 데이터만 추출
nan_df = df_1[df_1.isnull().any(1)]
nan_df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
24,20170811,130960,CJ E&M;(130960)디지털 성장이 돋보인 2분기,95000,buy,황성진,현대차투자증권,439553,NaN,NaN
40,20161024,002550,KB손해보험(002550),35000,buy,"장효선,이명준",삼성증권,395463,NaN,NaN
47,20150424,000830,삼성물산(000830),72000,buy,"박형렬,김예지",KDB대우증권,348721,NaN,NaN
88,20131031,028150,GS홈쇼핑(028150),320000,buy,김미연,유진증권,314193,NaN,NaN
115,20120516,037620,미래에셋증권(037620),46600,buy,-,신한금융,283137,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
21236,20111129,037620,미래에셋증권 (037620),52000,strongbuy,정보승,한화증권,273875,NaN,NaN
21237,20111129,003450,현대증권 (003450),10700,strongbuy,정보승,한화증권,273874,NaN,NaN
21255,20111114,000830,삼성물산 (000830),102000,strongbuy,조주형,교보증권,272740,NaN,NaN
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [18]:
df_1.to_csv('./csv/sampled_df_price21260.csv', encoding='utf-8-sig')

In [28]:
nan_df.to_csv('nan_df_2177.csv', encoding='utf-8-sig')

In [125]:
df = pd.read_csv('./csv/sampled_df_price21260.csv', index_col=0, dtype={'code':str, '작성일':str})
df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,88350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,92070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,35720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,20560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,97230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
21258,20111110,210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
21259,20111107,10620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"
21260,20111104,33630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [126]:
df['code'] = df['code'].apply(lambda x: x.zfill(6))

In [132]:
df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [136]:
df_nan = pd.read_csv('nan_df_2177.csv', index_col=0, dtype={'작성일':str, 'code':str})
df_nan['code'] =df_nan['code'].apply(lambda x: x.zfill(6))

In [137]:
df_nan

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
24,20170811,130960,CJ E&M;(130960)디지털 성장이 돋보인 2분기,95000,buy,황성진,현대차투자증권,439553,NaN,NaN
40,20161024,002550,KB손해보험(002550),35000,buy,"장효선,이명준",삼성증권,395463,NaN,NaN
47,20150424,000830,삼성물산(000830),72000,buy,"박형렬,김예지",KDB대우증권,348721,NaN,NaN
88,20131031,028150,GS홈쇼핑(028150),320000,buy,김미연,유진증권,314193,NaN,NaN
115,20120516,037620,미래에셋증권(037620),46600,buy,-,신한금융,283137,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
21236,20111129,037620,미래에셋증권 (037620),52000,strongbuy,정보승,한화증권,273875,NaN,NaN
21237,20111129,003450,현대증권 (003450),10700,strongbuy,정보승,한화증권,273874,NaN,NaN
21255,20111114,000830,삼성물산 (000830),102000,strongbuy,조주형,교보증권,272740,NaN,NaN
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [143]:
nan_unique_list=df_nan['code'].unique()

In [146]:
nan_unique_list

array(['130960', '002550', '000830', '028150', '037620', '001300',
       '053000', '000030', '068870', '010520', '016170', '005930',
       '094190', '033630', '213500', '210980', '138250', '021960',
       '138930', '139480', '117930', '195870', '214430', '004130',
       '023890', '108790', '068790', '214320', '004000', '003600',
       '000080', '000150', '008000', '005180', '031430', '030520',
       '024660', '161390', '105560', '097230', '041510', '003450',
       '010140', '950100', '055550', '005380', '155960', '078340',
       '192520', '123100', '214180', '139130', '005190', '028050',
       '000210', '091690', '097950', '035900', '000240', '048910',
       '112240', '004940', '024110', '010060', '010950', '123260',
       '032830', '066570', '069260', '010130', '036490', '053740',
       '006400', '000270', '002300', '020760', '034020', '011780',
       '012750', '035420', '030200', '011170', '033270', '064960',
       '086790', '064350', '079440', '009580', '004800', '300720',
       '192530', '025850', '012450', '000720', '057500', '036460',
       '011210', '055500', '131390', '017670', '103140', '051310',
       '032040', '000660', '900180', '257370', '007640', '236810',
       '381920', '037140', '294570', '301300', '218410', '241840',
       '027390', '012670', '311320', '376980', '102600', '278650',
       '282880', '197210', '034230', '214680', '322310', '217270',
       '043290', '277810', '003670', '204620', '012030', '229480',
       '136540', '144620', '140320', '293780', '290120', '290690',
       '950180', '361390', '129890', '280140', '375500', '226350',
       '300120', '297090', '009900', '356890', '256150', '275720',
       '293290', '308140', '148150', '348120', '152330', '257720',
       '111710', '361610', '217480', '215790', '228180', '950170',
       '100590', '337930', '290380', '302440', '138070', '382840',
       '273640', '010090', '234690', '161990', '190410', '099660',
       '030010', '352480', '214310', '051910', '008770', '030190',
       '126600', '187220', '145720', '179900', '222080', '036000',
       '069640', '235980', '090370', '293480', '011280', '066910',
       '234920', '100130', '239610', '159580', '092190', '054780',
       '138080', '085670', '376290', '317400', '046120', '267790',
       '322510', '311390', '234340', '288620', '018250', '016790',
       '326030', '367000', '333620', '137400', '321820', '195440',
       '377450', '042380', '041710', '306040', '178320', '131290',
       '228670', '252990', '195940', '131760', '123900', '164060',
       '149940', '039030', '220250', '038710', '314930', '348030',
       '248070', '317870', '357550', '138690', '003340', '033640',
       '271780', '138610', '268600', '376300', '210540', '134780',
       '031690', '086390', '104830', '194480', '217730', '207940',
       '046290', '361670', '215100', '300080', '212560', '347740',
       '204990', '010400', '299030', '065160', '221670', '220110',
       '300090', '194510', '297890', '357580', '381530', '305090',
       '262840', '298540', '192650', '173940', '004650', '060150',
       '090460', '064760', '052690', '130580', '900080', '131090',
       '158380', '215200', '352940', '108490', '213090', '137940',
       '217880', '008120', '086520', '183300', '276620', '245030',
       '272210', '060850', '289080', '099750', '215360', '950190',
       '214150', '238730', '377030', '274460', '104230', '331920',
       '316640', '110790', '290720', '381970', '122990', '071050',
       '094840', '285130', '000990', '114810', '002320', '004370',
       '067000', '101170', '009540', '170030', '036890', '031440',
       '064510', '064290', '205100', '245620', '019210', '029460',
       '304870', '040830', '247540', '192080', '304840', '018360',
       '084850', '217330', '266470', '372910', '204020', '137310',
       '330590', '139990', '278281', '047040', '078060', '290550',
       '216050', '163730', '377300', '259960', '219750', '215380',
       '008340', '307950', '276240', '103130', '299910', '104620',
       '111820', '061970', '317330', '329050', '067730', '352910',
       '357880', '014790', '263810', '208340', '167380', '038160',
       '340570', '012630', '020560', '002790', '011160', '033660',
       '011760', '068270', '090730', '128940', '023160', '006360',
       '067250', '033170', '011200', '088980', '064420', '042660',
       '066970', '006280', '023530', '006350', '088350', '063080',
       '035720', '018880', '123330', '006650', '000100', '037560',
       '225650', '051600', '006800', '029780', '204320', '180400',
       '019050', '035760', '096530', '161890', '089590', '051500',
       '000021', '032640', '181710', '005880', '073240', '034220',
       '060980', '071840', '043650', '000620', '005940', '042670'],
      dtype=object)

In [162]:
# 코드가 없어서 크롤링 하지 못한 것을 제외한 나머지 리스트들
error_list=[]
for nan_list in nan_unique_list:
    if len(df[df['code'] == nan_list])*2 != df[df['code'] == nan_list].isnull().sum().sum() :
        error_list.append(nan_list)

In [165]:
error_list

['005930',
 '213500',
 '210980',
 '138250',
 '138930',
 '139480',
 '195870',
 '214430',
 '068790',
 '214320',
 '004000',
 '000080',
 '000150',
 '005180',
 '031430',
 '030520',
 '161390',
 '105560',
 '097230',
 '041510',
 '010140',
 '055550',
 '005380',
 '078340',
 '214180',
 '139130',
 '028050',
 '000210',
 '097950',
 '035900',
 '000240',
 '048910',
 '024110',
 '010060',
 '010950',
 '032830',
 '066570',
 '069260',
 '010130',
 '036490',
 '006400',
 '000270',
 '020760',
 '034020',
 '011780',
 '012750',
 '035420',
 '030200',
 '011170',
 '033270',
 '064960',
 '086790',
 '064350',
 '009580',
 '004800',
 '012450',
 '000720',
 '036460',
 '011210',
 '131390',
 '017670',
 '103140',
 '000660',
 '257370',
 '236810',
 '294570',
 '218410',
 '241840',
 '278650',
 '282880',
 '034230',
 '214680',
 '322310',
 '217270',
 '003670',
 '204620',
 '012030',
 '136540',
 '293780',
 '290690',
 '950180',
 '361390',
 '129890',
 '375500',
 '300120',
 '009900',
 '256150',
 '148150',
 '111710',
 '361610',
 '217480',
 '215790',
 '950170',
 '100590',
 '337930',
 '302440',
 '138070',
 '234690',
 '352480',
 '051910',
 '008770',
 '030190',
 '126600',
 '187220',
 '145720',
 '179900',
 '222080',
 '036000',
 '069640',
 '235980',
 '090370',
 '293480',
 '066910',
 '234920',
 '100130',
 '239610',
 '159580',
 '092190',
 '054780',
 '138080',
 '376290',
 '317400',
 '046120',
 '267790',
 '311390',
 '234340',
 '288620',
 '018250',
 '367000',
 '333620',
 '137400',
 '321820',
 '377450',
 '306040',
 '178320',
 '131290',
 '228670',
 '252990',
 '131760',
 '164060',
 '039030',
 '248070',
 '317870',
 '138690',
 '033640',
 '138610',
 '210540',
 '086390',
 '104830',
 '194480',
 '217730',
 '207940',
 '215100',
 '212560',
 '347740',
 '010400',
 '299030',
 '297890',
 '305090',
 '298540',
 '192650',
 '173940',
 '004650',
 '060150',
 '090460',
 '064760',
 '052690',
 '130580',
 '215200',
 '352940',
 '108490',
 '137940',
 '217880',
 '086520',
 '183300',
 '272210',
 '060850',
 '099750',
 '215360',
 '950190',
 '214150',
 '331920',
 '110790',
 '290720',
 '381970',
 '122990',
 '071050',
 '094840',
 '285130',
 '000990',
 '002320',
 '004370',
 '067000',
 '101170',
 '009540',
 '170030',
 '036890',
 '031440',
 '064510',
 '064290',
 '205100',
 '245620',
 '019210',
 '029460',
 '247540',
 '192080',
 '084850',
 '217330',
 '204020',
 '137310',
 '330590',
 '047040',
 '290550',
 '216050',
 '163730',
 '219750',
 '215380',
 '307950',
 '299910',
 '104620',
 '061970',
 '317330',
 '014790',
 '263810',
 '208340',
 '012630',
 '020560',
 '002790',
 '011760',
 '068270',
 '128940',
 '023160',
 '006360',
 '033170',
 '011200',
 '088980',
 '042660',
 '066970',
 '006280',
 '023530',
 '088350',
 '063080',
 '035720',
 '018880',
 '123330',
 '006650',
 '000100',
 '037560',
 '051600',
 '006800',
 '029780',
 '204320',
 '035760',
 '096530',
 '161890',
 '089590',
 '051500',
 '032640',
 '181710',
 '005880',
 '073240',
 '034220',
 '060980',
 '071840',
 '043650',
 '005940',
 '042670']

In [196]:
nan_df[nan_df['code']=='213500']

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
609,20170714,213500,한솔제지(213500)상반기 부진을 하반기에 만회한다,28000,buy,박종렬,HMC투자증권,434940,"18,900","19,000"
9873,20190502,213500,한솔제지(213500)하반기 실적 개선 가능할 전망,23000,buy,박종렬,현대차투자증권,523150,NaN,NaN

In [169]:
import time
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, NoSuchWindowException
from selenium import webdriver

uri = 'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020103'
options = webdriver.ChromeOptions()
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko")
driver = webdriver.Chrome(options=options)
driver.get(uri)

In [197]:
for e_list in error_list:
    for i in nan_df[nan_df['code']== e_list].index:
        try:
            input_stock = driver.find_element_by_name('tboxisuCd_finder_stkisu0_0')
            input_st_dt = driver.find_element_by_name('strtDd')
            input_ed_dt = driver.find_element_by_name('endDd')
            input_stock.clear()
            input_st_dt.clear()
            input_ed_dt.clear()
            input_stock.send_keys(nan_df['code'].loc[i])
            input_st_dt.send_keys(nan_df['작성일'].loc[i])
            input_ed_dt.send_keys(nan_df['작성일'].loc[i])
            search_btn_1 = driver.find_element_by_id('btnisuCd_finder_stkisu0_0')
            search_btn_1.click()
            time.sleep(2.4)
            search_btn_2 = driver.find_element_by_id('jsSearchButton')
            search_btn_2.click()
            time.sleep(2.4)
            open_price = driver.find_element_by_xpath('//*[@id="jsMdiContent"]/div/div[1]/div[1]/div[1]/div[2]/div/div/table/tbody/tr/td[5]').text
            close_price = driver.find_element_by_xpath('//*[@id="jsMdiContent"]/div/div[1]/div[1]/div[1]/div[2]/div/div/table/tbody/tr/td[2]').text
            nan_df['시가'].loc[i] = open_price
            nan_df['종가'].loc[i] = close_price
            no_search = driver.find_element_by_xpath('//*[@id="jsGrid_div__finder_stkisu0_0"]/div/div/div[2]/div').text
            driver.find_element_by_xpath('//*[@id="jsLayer_finder_stkisu0_0"]/div[1]/button/span[1]').click()
            time.sleep(1)

            if no_search :
                nan_df['시가'].loc[i] = np.nan
                nan_df['종가'].loc[i] = np.nan
                time.sleep(1)

        except (NoSuchElementException, StaleElementReferenceException) as e :
            pass

C:\anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [171]:
# 20120526 토요일
nan_df[nan_df['code']=='005930']

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
402,20201030,005930,삼성전자(005930)투자에 대한 시각을 DRAM으로 옮겨야 할 시기,75000,buy,박유악,키움증권,574484,"58,000","56,600"
2069,20171128,005930,삼성전자(005930)업황 점검,3400000,buy,"도현우,이수연",미래에셋대우,454456,"2,635,000","2,664,000"
2717,20130729,005930,삼성전자(005930),1900000,buy,이정,유진증권,308439,"1,291,000","1,283,000"
6333,20120526,005930,삼성전자(005930),1950000,buy,"서원석,박기흥",한투증권,283558,NaN,NaN

In [198]:
for e_list in error_list:
    df = df.combine_first(nan_df[nan_df['code']==e_list])

In [204]:
df.to_csv('./csv/sampled_df_price21260_add.csv', encoding='utf-8-sig')

In [215]:
df = pd.read_csv('./csv/sampled_df_price21260_add.csv', index_col=0, dtype={'code':str, '작성일':str})
df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [209]:
df[df.isnull().any(1)].to_csv('nan_df_1007.csv', encoding='utf-8-sig')

In [216]:
df1 = pd.read_csv('nan_df_1007.csv', index_col=0, dtype={'code':str, '작성일':str})

In [217]:
df1['code'].nunique()

268

In [223]:
df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [225]:
df1['code'].nunique()

268

In [226]:
nan_unique_df1=df1['code'].unique()

In [227]:
no_code_list=[]
for nan_list in nan_unique_df1:
    if len(df[df['code'] == nan_list])*2 == df[df['code'] == nan_list].isnull().sum().sum() :
        no_code_list.append(nan_list)

In [229]:
# 종목 시가,종가가 모두 nan인 종목 수
# 종목이 상장폐지, 합병 등 종목 코드가 바뀐 경우
len(no_code_list)

159

In [230]:
error_code_list=[]
for nan_list in nan_unique_df1:
    if len(df[df['code'] == nan_list])*2 != df[df['code'] == nan_list].isnull().sum().sum() :
        error_code_list.append(nan_list)

In [232]:
# 시가, 종가가 하나라도 담긴 종목 수
# 일부 리포트가 주말 및 공휴일에 작성된 경우, 대부분 당시 상장예정 종목인 경우
len(error_code_list)

109

In [233]:
error_code_list

['161390',
 '010140',
 '214320',
 '138930',
 '000210',
 '214180',
 '006400',
 '000270',
 '139130',
 '005930',
 '000720',
 '000240',
 '036460',
 '011210',
 '103140',
 '000660',
 '257370',
 '236810',
 '294570',
 '241840',
 '278650',
 '282880',
 '322310',
 '293780',
 '290690',
 '950180',
 '361390',
 '129890',
 '300120',
 '009900',
 '256150',
 '148150',
 '111710',
 '361610',
 '950170',
 '100590',
 '337930',
 '302440',
 '234690',
 '352480',
 '376290',
 '092190',
 '317400',
 '311390',
 '234340',
 '288620',
 '018250',
 '367000',
 '333620',
 '321820',
 '377450',
 '306040',
 '228670',
 '252990',
 '164060',
 '248070',
 '317870',
 '207940',
 '215100',
 '347740',
 '010400',
 '299030',
 '297890',
 '305090',
 '298540',
 '192650',
 '130580',
 '218410',
 '352940',
 '108490',
 '235980',
 '272210',
 '060850',
 '099750',
 '950190',
 '331920',
 '110790',
 '290720',
 '381970',
 '138250',
 '205100',
 '293480',
 '247540',
 '084850',
 '217330',
 '204020',
 '330590',
 '290550',
 '163730',
 '307950',
 '299910',
 '104620',
 '317330',
 '014790',
 '263810',
 '208340',
 '011780',
 '128940',
 '052690',
 '011200',
 '139480',
 '000100',
 '037560',
 '035760',
 '051600',
 '043650',
 '210980',
 '035720',
 '005940']

In [371]:
for i, s in enumerate(error_code_list):
    print(i, s)

0 161390
1 010140
2 214320
3 138930
4 000210
5 214180
6 006400
7 000270
8 139130
9 005930
10 000720
11 000240
12 036460
13 011210
14 103140
15 000660
16 257370
17 236810
18 294570
19 241840
20 278650
21 282880
22 322310
23 293780
24 290690
25 950180
26 361390
27 129890
28 300120
29 009900
30 256150
31 148150
32 111710
33 361610
34 950170
35 100590
36 337930
37 302440
38 234690
39 352480
40 376290
41 092190
42 317400
43 311390
44 234340
45 288620
46 018250
47 367000
48 333620
49 321820
50 377450
51 306040
52 228670
53 252990
54 164060
55 248070
56 317870
57 207940
58 215100
59 347740
60 010400
61 299030
62 297890
63 305090
64 298540
65 192650
66 130580
67 218410
68 352940
69 108490
70 235980
71 272210
72 060850
73 099750
74 950190
75 331920
76 110790
77 290720
78 381970
79 138250
80 205100
81 293480
82 247540
83 084850
84 217330
85 204020
86 330590
87 290550
88 163730
89 307950
90 299910
91 104620
92 317330
93 014790
94 263810
95 208340
96 011780
97 128940
98 052690
99 011200
100 139480
101 000100
102 037560
103 035760
104 051600
105 043650
106 210980
107 035720
108 005940

In [413]:
# 상장 예정 종목
df[(df.code == '333620') & (df.시가.isnull())]

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
11515,20210315,333620,엔시스(333620) 글로벌 배터리 시장 성장성 + 배터리 기업들 경...,0,sell,정민구,하나금융투자,584710,NaN,NaN

In [426]:
for e_list in error_code_list[51:]:
    if len(df[(df.code == e_list) & (df.시가.isnull())].index) >= 1:
        for i in df[(df.code == e_list) & (df.시가.isnull())].index:
            try:
                input_stock = driver.find_element_by_name('tboxisuCd_finder_stkisu0_0')
                input_st_dt = driver.find_element_by_name('strtDd')
                input_ed_dt = driver.find_element_by_name('endDd')
                input_stock.clear()
                input_st_dt.clear()
                input_ed_dt.clear()
                input_stock.send_keys(df['code'].loc[i])
                input_st_dt.send_keys(df['작성일'].loc[i])
                input_ed_dt.send_keys(df['작성일'].loc[i])
                search_btn_1 = driver.find_element_by_id('btnisuCd_finder_stkisu0_0')
                search_btn_1.click()
                time.sleep(2.4)
                search_btn_2 = driver.find_element_by_id('jsSearchButton')
                search_btn_2.click()
                time.sleep(2.4)
                open_price = driver.find_element_by_xpath('//*[@id="jsMdiContent"]/div/div[1]/div[1]/div[1]/div[2]/div/div/table/tbody/tr/td[5]').text
                close_price = driver.find_element_by_xpath('//*[@id="jsMdiContent"]/div/div[1]/div[1]/div[1]/div[2]/div/div/table/tbody/tr/td[2]').text
                df['시가'].loc[i] = open_price
                df['종가'].loc[i] = close_price
                no_search = driver.find_element_by_xpath('//*[@id="jsGrid_div__finder_stkisu0_0"]/div/div/div[2]/div').text
                driver.find_element_by_xpath('//*[@id="jsLayer_finder_stkisu0_0"]/div[1]/button/span[1]').click()
                time.sleep(1)
                if no_search :
                    df['시가'].loc[i] = np.nan
                    df['종가'].loc[i] = np.nan
                    time.sleep(1)
            except (NoSuchElementException, StaleElementReferenceException) as e :
                        pass

C:\anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [432]:
df[df.isnull().any(1)].to_csv('nan_df_997.csv', encoding='utf-8-sig')

In [430]:
df.to_csv('./csv/sampled_df_price21260_add.csv', encoding='utf-8-sig')

In [436]:
df_2 = pd.read_csv('nan_df_997.csv', index_col=0, dtype={'code':str, '작성일':str})

In [440]:
df_2.code.nunique()

260