In [1]:
import pandas as pd
import numpy as np

In [5]:
nan_df = pd.read_csv('nan_df_997.csv', index_col=0, dtype={'code':str, '작성일':str})
nan_df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
24,20170811,130960,CJ E&M;(130960)디지털 성장이 돋보인 2분기,95000,buy,황성진,현대차투자증권,439553,NaN,NaN
40,20161024,002550,KB손해보험(002550),35000,buy,"장효선,이명준",삼성증권,395463,NaN,NaN
47,20150424,000830,삼성물산(000830),72000,buy,"박형렬,김예지",KDB대우증권,348721,NaN,NaN
88,20131031,028150,GS홈쇼핑(028150),320000,buy,김미연,유진증권,314193,NaN,NaN
115,20120516,037620,미래에셋증권(037620),46600,buy,-,신한금융,283137,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
21236,20111129,037620,미래에셋증권 (037620),52000,strongbuy,정보승,한화증권,273875,NaN,NaN
21237,20111129,003450,현대증권 (003450),10700,strongbuy,정보승,한화증권,273874,NaN,NaN
21255,20111114,000830,삼성물산 (000830),102000,strongbuy,조주형,교보증권,272740,NaN,NaN
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [9]:
df = pd.read_csv('./csv/sampled_df_price21260_add.csv', index_col=0, dtype={'code':str, '작성일':str})
df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,000830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"
21260,20111104,033630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [16]:
nan_unique_list = nan_df['code'].unique()

In [33]:
no_code_list=[]
for nan_list in nan_unique_list:
    if len(df[df['code'] == nan_list])*2 == df[df['code'] == nan_list].isnull().sum().sum() :
        no_code_list.append(nan_list)

In [34]:
# 종목 시가,종가가 날짜에 관계없이 모두 nan인 종목 수
# 종목이 상장폐지, 합병 등 종목 코드가 바뀐 경우 과거데이터 제공 안함
len(no_code_list)

159

In [39]:
no_code_list

['130960',
 '002550',
 '000830',
 '028150',
 '037620',
 '001300',
 '053000',
 '000030',
 '068870',
 '010520',
 '016170',
 '094190',
 '033630',
 '021960',
 '117930',
 '004130',
 '023890',
 '108790',
 '003600',
 '008000',
 '024660',
 '003450',
 '950100',
 '155960',
 '192520',
 '123100',
 '005190',
 '091690',
 '112240',
 '004940',
 '123260',
 '053740',
 '002300',
 '079440',
 '300720',
 '192530',
 '025850',
 '057500',
 '055500',
 '051310',
 '032040',
 '900180',
 '007640',
 '381920',
 '037140',
 '301300',
 '027390',
 '012670',
 '311320',
 '376980',
 '102600',
 '197210',
 '043290',
 '277810',
 '229480',
 '144620',
 '140320',
 '290120',
 '280140',
 '226350',
 '297090',
 '356890',
 '275720',
 '293290',
 '308140',
 '348120',
 '152330',
 '257720',
 '228180',
 '290380',
 '382840',
 '273640',
 '010090',
 '161990',
 '190410',
 '099660',
 '030010',
 '214310',
 '011280',
 '085670',
 '322510',
 '016790',
 '326030',
 '195440',
 '042380',
 '041710',
 '195940',
 '123900',
 '149940',
 '220250',
 '038710',
 '314930',
 '348030',
 '357550',
 '003340',
 '271780',
 '268600',
 '376300',
 '134780',
 '031690',
 '046290',
 '361670',
 '300080',
 '204990',
 '065160',
 '221670',
 '220110',
 '300090',
 '194510',
 '357580',
 '381530',
 '262840',
 '900080',
 '131090',
 '158380',
 '213090',
 '008120',
 '276620',
 '245030',
 '289080',
 '238730',
 '377030',
 '274460',
 '104230',
 '316640',
 '114810',
 '304870',
 '040830',
 '304840',
 '018360',
 '266470',
 '372910',
 '139990',
 '278281',
 '078060',
 '377300',
 '259960',
 '008340',
 '276240',
 '103130',
 '111820',
 '329050',
 '067730',
 '352910',
 '357880',
 '167380',
 '038160',
 '340570',
 '011160',
 '033660',
 '090730',
 '067250',
 '064420',
 '006350',
 '225650',
 '180400',
 '019050',
 '000021',
 '000620']

In [40]:
nan_df[nan_df['code'] == '130960']

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
24,20170811,130960,CJ E&M;(130960)디지털 성장이 돋보인 2분기,95000,buy,황성진,현대차투자증권,439553,NaN,NaN
138,20160511,130960,CJ E&M(130960),106000,buy,정윤미,미래에셋증권,379647,NaN,NaN
406,20170410,130960,CJ E&M;(130960)하나금융투자 Internet/Game/Media Weekly,110000,buy,"황승택,금가람",하나대투증권,419277,NaN,NaN
439,20161123,130960,CJ E&M;(130960),100000,buy,이남준,KTB투자증권,400235,NaN,NaN
716,20170914,130960,"CJ E&M;(130960) 잠시 쉬어가지만, 콘텐츠 제작역량 강화는 지속",95000,buy,김현용,이베스트증권,443824,NaN,NaN
1018,20130513,130960,CJ E&M(130960),44000,buy,"김시우,한상웅",한투증권,304173,NaN,NaN
1272,20170703,130960,CJ E&M;(130960)조금은 아쉬웠던 2분기,105000,buy,김현용,이베스트증권,433266,NaN,NaN
1456,20121016,130960,CJ E&M (130960),35000,buy,"최경진,홍서진",신한금융,291509,NaN,NaN
1566,20170209,130960,CJ E&M;(130960),95000,buy,김현용,이베스트증권,410608,NaN,NaN
1641,20130812,130960,CJ E&M (130960),48000,buy,이우승,유진증권,309375,NaN,NaN
1688,20160229,130960,CJ E&M(130960),110000,buy,"문지현,하누리",KDB대우증권,373649,NaN,NaN
2051,20150907,130960,CJ E&M(130960),106000,buy,정윤미,미래에셋증권,360181,NaN,NaN
2522,20150812,130960,CJ E&M(130960),100000,buy,"홍세종,성준원",신한금융투자,358408,NaN,NaN
3120,20121009,130960,CJ E&M(130960),38000,buy,이현정,SK증권,290998,NaN,NaN
3339,20160125,130960,CJ E&M(130960),120000,buy,김현용,이베스트증권,370973,NaN,NaN
3977,20180430,130960,CJ E&M(130960)예상했던 호실적. 이제 관심은 ‘콘텐츠 커머스’,120000,buy,"이남준,주윤혜",KTB투자증권,474812,NaN,NaN
4568,20180605,130960,CJ E&M(130960)긍정적인 합병 시너지,114000,buy,정지수,메리츠종금증권,480332,NaN,NaN
4794,20131223,130960,CJ E&M(130960),45000,buy,"신정현,이한엽",삼성증권,317194,NaN,NaN
4934,20121108,130960,CJ E&M(130960),36000,buy,김시우,한투증권,293566,NaN,NaN
5016,20161110,130960,CJ E&M;(130960),110000,buy,"문지현,하누리",미래에셋대우,398420,NaN,NaN
5296,20121112,130960,CJ E&M(130960),39000,buy,"민영상,황용주",하이증권,293738,NaN,NaN
5323,20150330,130960,CJ E&M(130960),70000,buy,문지현,KDB대우증권,346282,NaN,NaN
5466,20170512,130960,CJ E&M;(130960)일신우일신,125000,buy,"황승택,금가람",하나대투증권,424861,NaN,NaN
5665,20141113,130960,CJ E&M(130960),55000,buy,이창영,유안타증권,336650,NaN,NaN
5755,20150522,130960,CJ E&M(130960),84000,buy,김회재,대신증권,351545,NaN,NaN
5866,20161010,130960,CJ E&M(130960),100000,buy,임민규,현대증권,393594,NaN,NaN
7003,20140814,130960,CJ E&M(130960),70000,buy,이창영,동양증권,330733,NaN,NaN
8438,20170119,130960,CJ E&M;(130960),95000,buy,황성진,HMC투자증권,407150,NaN,NaN
8540,20160511,130960,CJ E&M(130960),100000,buy,임민규,현대증권,379665,NaN,NaN
8808,20160621,130960,CJ E&M(130960),110000,buy,문지현,미래에셋대우,383094,NaN,NaN
9283,20160108,130960,CJ E&M(130960),106000,buy,정윤미,미래에셋증권,369599,NaN,NaN
9396,20171122,130960,CJ E&M(130960)TV 플랫폼 재편의 선두 주자,100000,buy,김회재,대신증권,453633,NaN,NaN
9408,20151027,130960,CJ E&M(130960),120000,buy,이창영,유안타증권,364061,NaN,NaN
9506,20171020,130960,CJ E&M(130960)드래곤 가치 반영 진행 중,102000,buy,박정엽,미래에셋대우,447592,NaN,NaN
9669,20170810,130960,CJ E&M;(130960)수익성이 아쉬운 2분기 실적,98000,buy,이동륜,KB증권,439384,NaN,NaN
9697,20131210,130960,CJ E&M(130960),47000,buy,"박진,김혜련",우리증권,316742,NaN,NaN
9964,20171018,130960,CJ E&M(130960)콘텐츠 타깃팅 시대의 수혜주,100000,buy,김소혜,한화투자증권,447295,NaN,NaN
12188,20180717,130960,CJ E&M(130960)Coverage 제외,0,sell,이남준,KTB투자증권,485310,NaN,NaN
14512,20160224,130960,CJ E&M(130960),0,sell,김현용,이베스트증권,373441,NaN,NaN
15265,20140515,130960,CJ E&M(130960),52000,neutral,"민영상,황용주",하이증권,325425,NaN,NaN
15279,20120320,130960,CJ E&M(130960),34000,neutral,이우승,유진증권,279332,NaN,NaN
16479,20111129,130960,CJ E&M(130960),36000,neutral,"김동준,이우승",유진증권,273859,NaN,NaN
16659,20160511,130960,CJ E&M(130960),79000,neutral,김회재,대신증권,379629,NaN,NaN
17598,20120510,130960,CJ E&M (130960),34000,neutral,"신정현,임수빈",삼성증권,282591,NaN,NaN
17997,20120315,130960,CJ E&M (130960),37000,neutral,"신정현,임수빈",삼성증권,279164,NaN,NaN
18102,20120216,130960,CJ E&M(130960),34000,neutral,이우승,유진증권,277874,NaN,NaN
19926,20121120,130960,CJ E&M(130960),30000,neutral,이우승,유진증권,294488,NaN,NaN
20557,20160511,130960,CJ E&M(130960),105000,strongbuy,"양승우,정재훈",삼성증권,379664,NaN,NaN

In [35]:
error_code_list=[]
for nan_list in nan_unique_list:
    if len(df[df['code'] == nan_list])*2 != df[df['code'] == nan_list].isnull().sum().sum() :
        error_code_list.append(nan_list)

In [36]:
# 시가, 종가가 하나라도 담긴 종목 수
# 일부 리포트가 주말 및 공휴일에 작성된 경우, 대부분 당시 상장예정 종목인 경우
len(error_code_list)

101

In [43]:
error_code_list

['161390',
 '010140',
 '000210',
 '006400',
 '000270',
 '005930',
 '000720',
 '000240',
 '036460',
 '011210',
 '103140',
 '000660',
 '257370',
 '236810',
 '294570',
 '241840',
 '278650',
 '282880',
 '322310',
 '293780',
 '290690',
 '950180',
 '361390',
 '129890',
 '300120',
 '009900',
 '256150',
 '148150',
 '111710',
 '361610',
 '950170',
 '100590',
 '337930',
 '302440',
 '234690',
 '352480',
 '376290',
 '092190',
 '317400',
 '311390',
 '234340',
 '288620',
 '018250',
 '367000',
 '333620',
 '321820',
 '377450',
 '306040',
 '228670',
 '252990',
 '164060',
 '248070',
 '317870',
 '207940',
 '215100',
 '347740',
 '010400',
 '299030',
 '297890',
 '305090',
 '298540',
 '192650',
 '352940',
 '108490',
 '235980',
 '272210',
 '060850',
 '099750',
 '950190',
 '331920',
 '110790',
 '290720',
 '381970',
 '205100',
 '293480',
 '247540',
 '084850',
 '217330',
 '204020',
 '330590',
 '290550',
 '163730',
 '307950',
 '299910',
 '104620',
 '317330',
 '014790',
 '263810',
 '208340',
 '011780',
 '128940',
 '052690',
 '011200',
 '000100',
 '037560',
 '035760',
 '051600',
 '043650',
 '210980',
 '035720',
 '005940']

In [65]:
nan_df[nan_df['code'] =='000240'].index.to_list()

[7091]

In [68]:
nan_df[nan_df['code'] =='000720'].index.to_list()

[6840, 7906]

In [71]:
# error_code_list 데이터 수
i = 0
for error_li in error_code_list:
    i += len(nan_df[nan_df['code'] ==error_li].index.to_list())
print(i)

124

In [80]:
nan_df[nan_df['code'] =='000720'].index.to_list()

[6840, 7906]

In [78]:
nan_df.loc[[6840]].작성일.values[0]

'20170430'

In [115]:
# 공휴일 및 당시 상장예정 목록의 요일을 출력
day_list =[]
for error_li in error_code_list:
    for li in nan_df[nan_df['code'] == error_li].index.to_list():
        dates = nan_df.loc[[li]].작성일.values[0]
        temp = pd.Timestamp(dates)
        day=temp.day_name()
        day_list.append(day)
    print(li, day, temp)

1897 Sunday 2017-04-30 00:00:00
2027 Tuesday 2012-05-01 00:00:00
3240 Sunday 2017-04-30 00:00:00
4549 Tuesday 2012-05-01 00:00:00
4758 Saturday 2012-04-28 00:00:00
6333 Saturday 2012-05-26 00:00:00
7906 Tuesday 2012-05-01 00:00:00
7091 Tuesday 2012-05-01 00:00:00
7267 Saturday 2012-04-28 00:00:00
7428 Sunday 2017-04-30 00:00:00
8831 Tuesday 2012-05-01 00:00:00
9586 Saturday 2012-04-28 00:00:00
12144 Tuesday 2018-08-28 00:00:00
10106 Wednesday 2021-01-06 00:00:00
10119 Wednesday 2021-04-14 00:00:00
12586 Friday 2019-06-21 00:00:00
14471 Tuesday 2019-11-19 00:00:00
10198 Thursday 2019-07-18 00:00:00
10332 Wednesday 2021-02-03 00:00:00
14835 Thursday 2019-05-30 00:00:00
10577 Monday 2020-10-26 00:00:00
12107 Wednesday 2019-04-17 00:00:00
10586 Friday 2021-03-05 00:00:00
10600 Wednesday 2020-11-18 00:00:00
10626 Tuesday 2019-10-01 00:00:00
10635 Wednesday 2020-12-02 00:00:00
10703 Wednesday 2019-09-04 00:00:00
12273 Wednesday 2019-07-17 00:00:00
10911 Wednesday 2018-11-07 00:00:00
10918 Friday 2021-05-07 00:00:00
11752 Wednesday 2018-03-21 00:00:00
11047 Thursday 2018-11-29 00:00:00
12797 Friday 2020-07-31 00:00:00
11080 Wednesday 2021-03-17 00:00:00
11183 Tuesday 2019-09-24 00:00:00
11271 Friday 2021-05-07 00:00:00
11297 Thursday 2021-09-23 00:00:00
11332 Monday 2020-02-24 00:00:00
11341 Tuesday 2019-10-22 00:00:00
11379 Tuesday 2019-08-06 00:00:00
11873 Monday 2019-06-24 00:00:00
11419 Wednesday 2018-10-10 00:00:00
11442 Friday 2018-03-09 00:00:00
11514 Thursday 2021-07-22 00:00:00
11515 Monday 2021-03-15 00:00:00
11525 Tuesday 2021-01-26 00:00:00
11573 Thursday 2021-10-14 00:00:00
11639 Tuesday 2019-11-05 00:00:00
11682 Monday 2019-07-22 00:00:00
13281 Tuesday 2021-05-04 00:00:00
14083 Tuesday 2020-07-21 00:00:00
13296 Monday 2021-01-18 00:00:00
11946 Monday 2019-10-07 00:00:00
13703 Wednesday 2016-11-02 00:00:00
13160 Monday 2018-12-31 00:00:00
14419 Wednesday 2020-08-05 00:00:00
12549 Thursday 2018-08-30 00:00:00
12560 Wednesday 2020-11-04 00:00:00
12687 Monday 2020-06-08 00:00:00
12793 Tuesday 2019-06-04 00:00:00
12806 Thursday 2020-07-09 00:00:00
12823 Tuesday 2019-03-05 00:00:00
13075 Thursday 2020-11-26 00:00:00
13106 Monday 2018-12-31 00:00:00
13159 Thursday 2019-12-05 00:00:00
14287 Thursday 2019-10-24 00:00:00
13350 Tuesday 2020-07-28 00:00:00
13933 Tuesday 2019-03-05 00:00:00
13511 Wednesday 2020-08-05 00:00:00
13704 Friday 2020-07-24 00:00:00
14202 Tuesday 2018-09-11 00:00:00
13755 Tuesday 2018-09-11 00:00:00
13833 Tuesday 2021-09-28 00:00:00
13876 Friday 2016-12-30 00:00:00
13931 Friday 2018-09-28 00:00:00
13934 Wednesday 2019-02-27 00:00:00
13993 Wednesday 2019-11-06 00:00:00
14000 Tuesday 2018-11-06 00:00:00
14122 Wednesday 2018-07-04 00:00:00
14153 Monday 2019-09-30 00:00:00
14274 Tuesday 2018-12-04 00:00:00
14303 Monday 2021-01-18 00:00:00
14511 Tuesday 2019-03-19 00:00:00
14630 Friday 2018-11-16 00:00:00
14726 Tuesday 2019-01-15 00:00:00
14818 Wednesday 2019-07-17 00:00:00
14927 Sunday 2017-04-30 00:00:00
14930 Monday 2018-12-31 00:00:00
14931 Tuesday 2018-11-06 00:00:00
15352 Sunday 2017-04-30 00:00:00
15488 Friday 2016-12-30 00:00:00
15739 Saturday 2012-04-28 00:00:00
15819 Saturday 2012-04-28 00:00:00
17137 Sunday 2017-04-30 00:00:00
17166 Sunday 2017-04-30 00:00:00
18636 Saturday 2012-04-28 00:00:00
19962 Saturday 2012-04-28 00:00:00
19993 Tuesday 2012-05-01 00:00:00
20704 Monday 2015-06-22 00:00:00
21119 Tuesday 2012-05-01 00:00:00
21121 Tuesday 2012-05-01 00:00:00

In [111]:
len(day_list)

124

In [112]:
day_list

['Sunday',
 'Tuesday',
 'Sunday',
 'Tuesday',
 'Saturday',
 'Saturday',
 'Sunday',
 'Tuesday',
 'Tuesday',
 'Saturday',
 'Sunday',
 'Tuesday',
 'Saturday',
 'Wednesday',
 'Tuesday',
 'Wednesday',
 'Wednesday',
 'Wednesday',
 'Monday',
 'Friday',
 'Wednesday',
 'Tuesday',
 'Tuesday',
 'Thursday',
 'Wednesday',
 'Tuesday',
 'Thursday',
 'Monday',
 'Wednesday',
 'Wednesday',
 'Wednesday',
 'Friday',
 'Wednesday',
 'Tuesday',
 'Wednesday',
 'Wednesday',
 'Tuesday',
 'Wednesday',
 'Wednesday',
 'Friday',
 'Wednesday',
 'Wednesday',
 'Thursday',
 'Thursday',
 'Friday',
 'Wednesday',
 'Tuesday',
 'Friday',
 'Thursday',
 'Monday',
 'Tuesday',
 'Tuesday',
 'Monday',
 'Monday',
 'Wednesday',
 'Friday',
 'Thursday',
 'Monday',
 'Tuesday',
 'Thursday',
 'Tuesday',
 'Monday',
 'Thursday',
 'Tuesday',
 'Monday',
 'Tuesday',
 'Monday',
 'Monday',
 'Monday',
 'Wednesday',
 'Wednesday',
 'Friday',
 'Monday',
 'Tuesday',
 'Wednesday',
 'Thursday',
 'Wednesday',
 'Monday',
 'Tuesday',
 'Thursday',
 'Tuesday',
 'Thursday',
 'Monday',
 'Thursday',
 'Tuesday',
 'Thursday',
 'Tuesday',
 'Wednesday',
 'Tuesday',
 'Tuesday',
 'Wednesday',
 'Friday',
 'Friday',
 'Tuesday',
 'Tuesday',
 'Tuesday',
 'Friday',
 'Friday',
 'Wednesday',
 'Wednesday',
 'Tuesday',
 'Wednesday',
 'Monday',
 'Tuesday',
 'Monday',
 'Tuesday',
 'Friday',
 'Tuesday',
 'Wednesday',
 'Sunday',
 'Monday',
 'Tuesday',
 'Sunday',
 'Friday',
 'Saturday',
 'Saturday',
 'Sunday',
 'Sunday',
 'Saturday',
 'Saturday',
 'Tuesday',
 'Monday',
 'Tuesday',
 'Tuesday']

In [107]:
day_list.count('Sunday')

8

In [108]:
day_list.count('Saturday')

8

In [ ]:
# 주말 및 공휴일을 제외한 나머지 상장 전 데이터는 삭제
# KRX에는 코드 없어진 과거데이터 제공 안함

In [116]:
no_code_list

['130960',
 '002550',
 '000830',
 '028150',
 '037620',
 '001300',
 '053000',
 '000030',
 '068870',
 '010520',
 '016170',
 '094190',
 '033630',
 '021960',
 '117930',
 '004130',
 '023890',
 '108790',
 '003600',
 '008000',
 '024660',
 '003450',
 '950100',
 '155960',
 '192520',
 '123100',
 '005190',
 '091690',
 '112240',
 '004940',
 '123260',
 '053740',
 '002300',
 '079440',
 '300720',
 '192530',
 '025850',
 '057500',
 '055500',
 '051310',
 '032040',
 '900180',
 '007640',
 '381920',
 '037140',
 '301300',
 '027390',
 '012670',
 '311320',
 '376980',
 '102600',
 '197210',
 '043290',
 '277810',
 '229480',
 '144620',
 '140320',
 '290120',
 '280140',
 '226350',
 '297090',
 '356890',
 '275720',
 '293290',
 '308140',
 '348120',
 '152330',
 '257720',
 '228180',
 '290380',
 '382840',
 '273640',
 '010090',
 '161990',
 '190410',
 '099660',
 '030010',
 '214310',
 '011280',
 '085670',
 '322510',
 '016790',
 '326030',
 '195440',
 '042380',
 '041710',
 '195940',
 '123900',
 '149940',
 '220250',
 '038710',
 '314930',
 '348030',
 '357550',
 '003340',
 '271780',
 '268600',
 '376300',
 '134780',
 '031690',
 '046290',
 '361670',
 '300080',
 '204990',
 '065160',
 '221670',
 '220110',
 '300090',
 '194510',
 '357580',
 '381530',
 '262840',
 '900080',
 '131090',
 '158380',
 '213090',
 '008120',
 '276620',
 '245030',
 '289080',
 '238730',
 '377030',
 '274460',
 '104230',
 '316640',
 '114810',
 '304870',
 '040830',
 '304840',
 '018360',
 '266470',
 '372910',
 '139990',
 '278281',
 '078060',
 '377300',
 '259960',
 '008340',
 '276240',
 '103130',
 '111820',
 '329050',
 '067730',
 '352910',
 '357880',
 '167380',
 '038160',
 '340570',
 '011160',
 '033660',
 '090730',
 '067250',
 '064420',
 '006350',
 '225650',
 '180400',
 '019050',
 '000021',
 '000620']

In [119]:
nan_df[nan_df['code'] == '002550']

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
40,20161024,002550,KB손해보험(002550),35000,buy,"장효선,이명준",삼성증권,395463,NaN,NaN
940,20170112,002550,KB손해보험(002550),32000,buy,"오진원,임수연",하나대투증권,405917,NaN,NaN
1129,20150430,002550,LIG손해보험(002550),41000,buy,강승건,대신증권,349389,NaN,NaN
1310,20170110,002550,KB손해보험(002550),35000,buy,김태현,키움증권,405504,NaN,NaN
1403,20161004,002550,KB손해보험(002550),35000,buy,"윤태호,김서연",한국투자증권,392953,NaN,NaN
1450,20160218,002550,KB손해보험(002550),43000,buy,강승건,대신증권,372949,NaN,NaN
1601,20120529,002550,LIG손해보험 (002550),37000,buy,윤태호,NH증권,283578,NaN,NaN
1612,20120529,002550,LIG손해보험 (002550),36000,buy,"한승희,장보람",우리증권,283626,NaN,NaN
1843,20161123,002550,KB손해보험(002550),34600,buy,성용훈,한화투자증권,400406,NaN,NaN
1870,20170203,002550,KB손해보험(002550),40300,buy,"김진상,정태준",HMC투자증권,409459,NaN,NaN
2021,20141013,002550,LIG손해보험(002550),35000,buy,"장효선,김재우",삼성증권,333770,NaN,NaN
2063,20170413,002550,KB손해보험(002550)1Q17 Preview – 불확실성 해소구간인 2...,35000,buy,"윤태호,최슬아",한국투자증권,420311,NaN,NaN
2101,20130902,002550,LIG손해보험(002550),31000,buy,윤제민,메리츠증권,310417,NaN,NaN
2458,20150717,002550,LIG손해보험(002550),35000,buy,박혜진,교보증권,356016,NaN,NaN
2808,20161004,002550,KB손해보험(002550),38000,buy,이남석,KTB투자증권,392802,NaN,NaN
2886,20160422,002550,KB손해보험(002550),40000,buy,"김고은,배연진",메리츠종금증권,377777,NaN,NaN
2925,20161108,002550,KB손해보험(002550),35000,buy,"윤태호,김서연",한국투자증권,397963,NaN,NaN
2953,20130902,002550,LIG손해보험(002550),31000,buy,이철호,한투증권,310432,NaN,NaN
2974,20120629,002550,LIG손해보험 (002550),36000,buy,한승희,우리증권,285319,NaN,NaN
3152,20161004,002550,KB손해보험(002550),39000,buy,서보익,유진투자증권,392957,NaN,NaN
3727,20120801,002550,LIG손해보험(002550),37500,buy,강승건,대신증권,287544,NaN,NaN
4087,20131001,002550,LIG 손해보험(002550),33000,buy,원재웅,동양증권,311765,NaN,NaN
4885,20151110,002550,KB손해보험(002550),35000,buy,박혜진,교보증권,365440,NaN,NaN
4975,20170403,002550,KB손해보험(002550)2월 실적 Review: 일평균 장기위험손해율 개...,33000,buy,김태현,키움증권,418194,NaN,NaN
5005,20130117,002550,LIG손해보험(002550),36000,buy,"이철호,송희정",한투증권,297144,NaN,NaN
5038,20120201,002550,LIG손해보험 (002550),34000,buy,"장효선,민경완",삼성증권,276649,NaN,NaN
5250,20150302,002550,LIG손해보험(002550),30000,buy,"장효선,신동오",삼성증권,344260,NaN,NaN
5346,20130719,002550,LIG손해보험(002550),31000,buy,이철호,한투증권,307778,NaN,NaN
5857,20141126,002550,LIG손해보험(002550),34000,buy,"송인찬,이관희",신한금융투자,337625,NaN,NaN
6378,20140102,002550,LIG손해보험(002550),40600,buy,한승희,우리증권,317443,NaN,NaN
7858,20121024,002550,LIG손해보험(002550),31000,buy,이치영,이트레이드증권,292119,NaN,NaN
7860,20140225,002550,LIG손해보험(002550),39000,buy,윤제민,메리츠증권,320717,NaN,NaN
7955,20141110,002550,LIG손해보험(002550),35000,buy,박혜진,교보증권,336404,NaN,NaN
8007,20140416,002550,LIG손해보험(002550),40600,buy,한승희,우리증권,323430,NaN,NaN
8641,20140502,002550,LIG손해보험(002550),38000,buy,"이철호,박석규",한투증권,324690,NaN,NaN
8715,20140113,002550,LIG손해보험(002550),40000,buy,"송인찬,이관희",신한금융,318019,NaN,NaN
9598,20150914,002550,KB손해보험(002550),36000,buy,정준섭,유안타증권,360622,NaN,NaN
9750,20131120,002550,LIG손해보험(002550),38000,buy,"장효선,신동오",삼성증권,315740,NaN,NaN
9854,20150102,002550,LIG손해보험(002550),41000,buy,강승건,대신증권,339554,NaN,NaN
11353,20170620,002550,KB손해보험(002550)Coverage 제외,0,sell,이남석,KTB투자증권,431342,NaN,NaN
15319,20151125,002550,KB손해보험(002550),0,neutral,"정길원,김주현",KDB대우증권,367090,NaN,NaN
16461,20150302,002550,LIG손해보험(002550),29000,neutral,이신영,HMC투자증권,344221,NaN,NaN
17548,20131101,002550,LIG손해보험(002550),29000,neutral,"이태경,한기현",현대증권,314290,NaN,NaN
18383,20161229,002550,KB손해보험(002550),26800,neutral,성용훈,한화투자증권,403967,NaN,NaN
18552,20151119,002550,KB손해보험(002550),0,neutral,"정길원,김주현",KDB대우증권,366563,NaN,NaN
20887,20131120,002550,LIG손해보험(002550),40000,strongbuy,"이태경,한기현",현대증권,315722,NaN,NaN

In [120]:
# 현재는 없어진 코드 데이터 수 873
j = 0
for no_li in no_code_list:
    j += len(nan_df[nan_df['code'] ==no_li].index.to_list())
print(j)

873

In [ ]:
# 주말 및 공휴일만 남기고 나머지 데이터는 모두 삭제

In [ ]:
# KRX 휴장일 데이터를 가져오기

In [208]:
# pip install exchange_calendars
import exchange_calendars as ecals

XKRX = ecals.get_calendar("XKRX") # 한국 코드
print(XKRX.is_session("20210919")) # 2021-09-19 은 개장일인지 확인
print(XKRX.previous_open(pd.Timestamp('20210919'))) # 이전 개장일은 언제인지 확인
print(XKRX.)

False
2021-09-17 00:00:00+00:00

In [134]:
import os
path = './csv/'
file_list = os.listdir(path)
holiday = [file for file in file_list if file.startswith('data')]

In [135]:
holiday

['data_2011.xls',
 'data_2012.xls',
 'data_2013.xls',
 'data_2014.xls',
 'data_2015.xls',
 'data_2016.xls',
 'data_2017.xls',
 'data_2018.xls',
 'data_2019.xls',
 'data_2020.xls',
 'data_2021.xls']

In [136]:
df = pd.DataFrame()
for i in holiday:
    data = pd.read_excel(path+i)
    df = pd.concat([df, data])
df = df.reset_index(drop=True)

In [137]:
# 2011~2021년 휴장일 데이터
df

              일자 및 요일    요일구분         비고
0    2011-02-02 (WED)  수요일           NaN
1    2011-02-03 (THU)  목요일           NaN
2    2011-02-04 (FRI)  금요일           NaN
3    2011-03-01 (TUE)  화요일           NaN
4    2011-05-05 (THU)  목요일           NaN
..                ...     ...        ...
154        2021-09-21  화요일            추석
155        2021-09-22  수요일            추석
156        2021-10-04  월요일     개천절(대체휴일)
157        2021-10-11  월요일     한글날(대체휴일)
158        2021-12-31  금요일         연말휴장일

[159 rows x 3 columns]

In [141]:
df.columns=['일자', '요일', '비고']
df

                   일자      요일         비고
0    2011-02-02 (WED)  수요일           NaN
1    2011-02-03 (THU)  목요일           NaN
2    2011-02-04 (FRI)  금요일           NaN
3    2011-03-01 (TUE)  화요일           NaN
4    2011-05-05 (THU)  목요일           NaN
..                ...     ...        ...
154        2021-09-21  화요일            추석
155        2021-09-22  수요일            추석
156        2021-10-04  월요일     개천절(대체휴일)
157        2021-10-11  월요일     한글날(대체휴일)
158        2021-12-31  금요일         연말휴장일

[159 rows x 3 columns]

In [153]:
df = df.fillna('-')

In [154]:
df['일자'] = df['일자'].apply(lambda x:x[:10])

In [156]:
df.to_csv('./csv/2011_2021_holiday.csv', encoding='utf-8-sig')

In [158]:
df_hol = pd.read_csv('./csv/2011_2021_holiday.csv', index_col=0)

In [160]:
df_hol.isnull().sum()

일자    0
요일    0
비고    0
dtype: int64

In [163]:
df_hol['일자'] = df_hol['일자'].apply(lambda x:''.join(x.split('-')))

In [164]:
df_hol

           일자      요일         비고
0    20110202  수요일             -
1    20110203  목요일             -
2    20110204  금요일             -
3    20110301  화요일             -
4    20110505  목요일             -
..        ...     ...        ...
154  20210921  화요일            추석
155  20210922  수요일            추석
156  20211004  월요일     개천절(대체휴일)
157  20211011  월요일     한글날(대체휴일)
158  20211231  금요일         연말휴장일

[159 rows x 3 columns]

In [165]:
error_code_list

['161390',
 '010140',
 '000210',
 '006400',
 '000270',
 '005930',
 '000720',
 '000240',
 '036460',
 '011210',
 '103140',
 '000660',
 '257370',
 '236810',
 '294570',
 '241840',
 '278650',
 '282880',
 '322310',
 '293780',
 '290690',
 '950180',
 '361390',
 '129890',
 '300120',
 '009900',
 '256150',
 '148150',
 '111710',
 '361610',
 '950170',
 '100590',
 '337930',
 '302440',
 '234690',
 '352480',
 '376290',
 '092190',
 '317400',
 '311390',
 '234340',
 '288620',
 '018250',
 '367000',
 '333620',
 '321820',
 '377450',
 '306040',
 '228670',
 '252990',
 '164060',
 '248070',
 '317870',
 '207940',
 '215100',
 '347740',
 '010400',
 '299030',
 '297890',
 '305090',
 '298540',
 '192650',
 '352940',
 '108490',
 '235980',
 '272210',
 '060850',
 '099750',
 '950190',
 '331920',
 '110790',
 '290720',
 '381970',
 '205100',
 '293480',
 '247540',
 '084850',
 '217330',
 '204020',
 '330590',
 '290550',
 '163730',
 '307950',
 '299910',
 '104620',
 '317330',
 '014790',
 '263810',
 '208340',
 '011780',
 '128940',
 '052690',
 '011200',
 '000100',
 '037560',
 '035760',
 '051600',
 '043650',
 '210980',
 '035720',
 '005940']

In [193]:
# 휴장일 리스트 13개
holi_list = []
for error_li in error_code_list:
    for li in nan_df[nan_df['code'] == error_li].index.to_list():
        dates = nan_df.loc[[li]].작성일.values[0]
        temp = pd.Timestamp(dates)
        day=temp.day_name()        
        if nan_df.loc[[li]].작성일.values[0] in list(df_hol['일자']):
            holi_list.append(li)
            print(li, day, temp)

2027 Tuesday 2012-05-01 00:00:00
4549 Tuesday 2012-05-01 00:00:00
7906 Tuesday 2012-05-01 00:00:00
7091 Tuesday 2012-05-01 00:00:00
8831 Tuesday 2012-05-01 00:00:00
13160 Monday 2018-12-31 00:00:00
13106 Monday 2018-12-31 00:00:00
13876 Friday 2016-12-30 00:00:00
14930 Monday 2018-12-31 00:00:00
15488 Friday 2016-12-30 00:00:00
19993 Tuesday 2012-05-01 00:00:00
21119 Tuesday 2012-05-01 00:00:00
21121 Tuesday 2012-05-01 00:00:00

In [192]:
holi_list

[2027,
 4549,
 7906,
 7091,
 8831,
 13160,
 13106,
 13876,
 14930,
 15488,
 19993,
 21119,
 21121]

In [183]:
len(holi_list)

13

In [194]:
# 주말 리스트 16개
weekend_list = []
for error_li in error_code_list:
    for li in nan_df[nan_df['code'] == error_li].index.to_list():
        dates = nan_df.loc[[li]].작성일.values[0]
        temp = pd.Timestamp(dates)
        day=temp.day_name()
        if day == 'Sunday' or day == 'Saturday':
            weekend_list.append(li)
            print(li, day, temp)

1897 Sunday 2017-04-30 00:00:00
3240 Sunday 2017-04-30 00:00:00
4758 Saturday 2012-04-28 00:00:00
6333 Saturday 2012-05-26 00:00:00
6840 Sunday 2017-04-30 00:00:00
7267 Saturday 2012-04-28 00:00:00
7428 Sunday 2017-04-30 00:00:00
9586 Saturday 2012-04-28 00:00:00
14927 Sunday 2017-04-30 00:00:00
15352 Sunday 2017-04-30 00:00:00
15739 Saturday 2012-04-28 00:00:00
15819 Saturday 2012-04-28 00:00:00
17137 Sunday 2017-04-30 00:00:00
17166 Sunday 2017-04-30 00:00:00
18636 Saturday 2012-04-28 00:00:00
19962 Saturday 2012-04-28 00:00:00

In [195]:
weekend_list

[1897,
 3240,
 4758,
 6333,
 6840,
 7267,
 7428,
 9586,
 14927,
 15352,
 15739,
 15819,
 17137,
 17166,
 18636,
 19962]

In [197]:
len(holi_list + weekend_list)

29

In [210]:
hl_wk_list = holi_list + weekend_list

In [213]:
hl_wk_list

[2027,
 4549,
 7906,
 7091,
 8831,
 13160,
 13106,
 13876,
 14930,
 15488,
 19993,
 21119,
 21121,
 1897,
 3240,
 4758,
 6333,
 6840,
 7267,
 7428,
 9586,
 14927,
 15352,
 15739,
 15819,
 17137,
 17166,
 18636,
 19962]

In [218]:
# pip install exchange_calendars
import exchange_calendars as ecals

XKRX = ecals.get_calendar("XKRX") # 한국 코드
print(XKRX.is_session("20210922")) # 2021-09-20 은 개장일인지 확인 True,False 반환
print(XKRX.previous_open(pd.Timestamp('20210922'))) # 이전 개장일은 언제인지 확인 TimeStamp형태로 반환

False
2021-09-17 00:00:00+00:00

In [323]:
# 공휴일 및 주말 데이터들을 이전 개장일 날짜를 가져온다
s = set()
for li in hl_wk_list:
    day = nan_df.loc[[li]].작성일.values[0]
    XKRX = ecals.get_calendar("XKRX")
    if XKRX.is_session(day) == False :
        preday = ''.join(str(XKRX.previous_open(pd.Timestamp(day)))[:10].split('-'))
        s.update([(li, preday)])

In [321]:
s

{(1897, '20170428'),
 (2027, '20120430'),
 (3240, '20170428'),
 (4549, '20120430'),
 (4758, '20120427'),
 (6333, '20120525'),
 (6840, '20170428'),
 (7091, '20120430'),
 (7267, '20120427'),
 (7428, '20170428'),
 (7906, '20120430'),
 (8831, '20120430'),
 (9586, '20120427'),
 (13106, '20181228'),
 (13160, '20181228'),
 (13876, '20161229'),
 (14927, '20170428'),
 (14930, '20181228'),
 (15352, '20170428'),
 (15488, '20161229'),
 (15739, '20120427'),
 (15819, '20120427'),
 (17137, '20170428'),
 (17166, '20170428'),
 (18636, '20120427'),
 (19962, '20120427'),
 (19993, '20120430'),
 (21119, '20120430'),
 (21121, '20120430')}

In [316]:
nan_df_29=nan_df.loc[hl_wk_list].sort_index(ascending=True)

In [317]:
nan_df_29

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
1897,20170430,161390,한국타이어(161390)불황기에 잘한 회사가 호황기에 더 잘한다,77000,buy,"김진우,박성준",한국투자증권,423555,NaN,NaN
2027,20120501,010140,삼성중공업 (010140),48000,buy,"한영수,장재연",삼성증권,281932,NaN,NaN
3240,20170430,000210,대림산업(000210)매력적인 이익 안정성,110000,buy,박상연,신한금융투자,423605,NaN,NaN
4549,20120501,006400,삼성SDI (006400),210000,buy,최지수,교보증권,281833,NaN,NaN
4758,20120428,000270,기아차 (000270),93000,buy,최중혁,신한금융,281670,NaN,NaN
6333,20120526,005930,삼성전자(005930),1950000,buy,"서원석,박기흥",한투증권,283558,NaN,NaN
6840,20170430,000720,현대건설(000720)하반기 신흥시장 매출 증가로 수익성 개선 전망,55000,buy,라진성,키움증권,423529,NaN,NaN
7091,20120501,000240,한국타이어 (000240),55000,buy,윤필중,삼성증권,281934,NaN,NaN
7267,20120428,036460,한국가스공사 (036460),52000,buy,"신민석,홍진주",신한금융,281666,NaN,NaN
7428,20170430,011210,현대위아(011210)하반기 턴어라운드 예상,77000,buy,박인우,미래에셋대우,423594,NaN,NaN
7906,20120501,000720,현대건설 (000720),102000,buy,"허문욱,이경신",KB증권,281842,NaN,NaN
8831,20120501,103140,풍산 (103140),42000,buy,김민수,삼성증권,281933,NaN,NaN
9586,20120428,000660,SK하이닉스 (000660),39000,buy,"진성혜,이현희",현대증권,281634,NaN,NaN
13106,20181231,108490,로보티즈(108490)서비스용 로봇 산업의 고성장 수혜,0,sell,김재훈,미래에셋대우,506957,NaN,NaN
13160,20181231,215100,로보로보(215100)세계로 도약이 기대되는 교육용 로봇 업체,0,sell,"김두현,이정기",하나금융투자,506928,NaN,NaN
13876,20161230,205100,엑셈(205100),0,sell,이성빈,교보증권,404018,NaN,NaN
14927,20170430,014790,한라(014790)현금이 들어오고 투자가 시작된다!,0,sell,라진성,키움증권,423527,NaN,NaN
14930,20181231,263810,상신전자(263810)긍정적인 주주환원 정책,0,sell,박원재,미래에셋대우,506951,NaN,NaN
15352,20170430,011780,금호석유(011780)티끌 모아 태산,80000,neutral,윤성노,대신증권,423565,NaN,NaN
15488,20161230,128940,한미약품(128940),450000,neutral,"서근희,정다은",대신증권,404022,NaN,NaN
15739,20120428,052690,한전기술 (052690),80000,neutral,"신민석,홍진주",신한금융,281667,NaN,NaN
15819,20120428,011200,현대상선 (011200),32000,neutral,"신민석,홍진주",신한금융,281665,NaN,NaN
17137,20170430,000100,유한양행(000100)1Q17 Review,275000,neutral,신재훈,이베스트증권,423616,NaN,NaN
17166,20170430,037560,CJ헬로비전(037560)1Q17 Review,9000,neutral,김현용,이베스트증권,423611,NaN,NaN
18636,20120428,035760,CJ오쇼핑(035760),240000,neutral,"이상구,태윤선",현대증권,281633,NaN,NaN
19962,20120428,051600,한전 KPS (051600),40000,neutral,"신민석,홍진주",신한금융,281668,NaN,NaN
19993,20120501,043650,국순당(043650),8500,neutral,"유 진,한지훈",현대증권,281929,NaN,NaN
21119,20120501,035720,다음 (035720),200000,strongbuy,김진구,NH증권,281944,NaN,NaN
21121,20120501,005940,우리투자증권 (005940),13000,strongbuy,박석현,한화증권,281887,NaN,NaN

In [318]:
import time
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, NoSuchWindowException
from selenium import webdriver

uri = 'http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020103'
options = webdriver.ChromeOptions()
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko")
driver = webdriver.Chrome(options=options)
driver.get(uri)

In [329]:
# 날짜만 바꿔서 KRX에서 크롤링해준다.
for i in nan_df_29.index[13:16]:
    try:
        input_stock = driver.find_element_by_name('tboxisuCd_finder_stkisu0_0')
        input_st_dt = driver.find_element_by_name('strtDd')
        input_ed_dt = driver.find_element_by_name('endDd')
        input_stock.clear()
        input_st_dt.clear()
        input_ed_dt.clear()
        input_stock.send_keys(nan_df_29['code'].loc[i])
        day=nan_df_29['작성일'].loc[i]
        input_st_dt.send_keys(''.join(str(XKRX.previous_open(pd.Timestamp(day)))[:10].split('-')))
        input_ed_dt.send_keys(''.join(str(XKRX.previous_open(pd.Timestamp(day)))[:10].split('-')))
        search_btn_1 = driver.find_element_by_id('btnisuCd_finder_stkisu0_0')
        search_btn_1.click()
        time.sleep(2.4)
        search_btn_2 = driver.find_element_by_id('jsSearchButton')
        search_btn_2.click()
        time.sleep(2.4)
        open_price = driver.find_element_by_xpath('//*[@id="jsMdiContent"]/div/div[1]/div[1]/div[1]/div[2]/div/div/table/tbody/tr/td[5]').text
        close_price = driver.find_element_by_xpath('//*[@id="jsMdiContent"]/div/div[1]/div[1]/div[1]/div[2]/div/div/table/tbody/tr/td[2]').text
        nan_df_29['시가'].loc[i] = open_price
        nan_df_29['종가'].loc[i] = close_price
        no_search = driver.find_element_by_xpath('//*[@id="jsGrid_div__finder_stkisu0_0"]/div/div/div[2]/div').text
        driver.find_element_by_xpath('//*[@id="jsLayer_finder_stkisu0_0"]/div[1]/button/span[1]').click()
        time.sleep(1)

        if no_search :
            nan_df_29['시가'].loc[i] = np.nan
            nan_df_29['종가'].loc[i] = np.nan
            time.sleep(1)
            
    except (NoSuchElementException, StaleElementReferenceException) as e :
        pass

In [326]:
''.join(str(XKRX.previous_open(pd.Timestamp('20181231')))[:10].split('-'))

'20181228'

In [330]:
nan_df_29

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
1897,20170430,161390,한국타이어(161390)불황기에 잘한 회사가 호황기에 더 잘한다,77000,buy,"김진우,박성준",한국투자증권,423555,"59,300","58,900"
2027,20120501,010140,삼성중공업 (010140),48000,buy,"한영수,장재연",삼성증권,281932,"40,800","41,700"
3240,20170430,000210,대림산업(000210)매력적인 이익 안정성,110000,buy,박상연,신한금융투자,423605,"80,900","80,300"
4549,20120501,006400,삼성SDI (006400),210000,buy,최지수,교보증권,281833,"153,500","163,000"
4758,20120428,000270,기아차 (000270),93000,buy,최중혁,신한금융,281670,"80,400","80,700"
6333,20120526,005930,삼성전자(005930),1950000,buy,"서원석,박기흥",한투증권,283558,"1,233,000","1,225,000"
6840,20170430,000720,현대건설(000720)하반기 신흥시장 매출 증가로 수익성 개선 전망,55000,buy,라진성,키움증권,423529,"49,250","48,550"
7091,20120501,000240,한국타이어 (000240),55000,buy,윤필중,삼성증권,281934,"46,000","47,900"
7267,20120428,036460,한국가스공사 (036460),52000,buy,"신민석,홍진주",신한금융,281666,"41,400","42,900"
7428,20170430,011210,현대위아(011210)하반기 턴어라운드 예상,77000,buy,박인우,미래에셋대우,423594,"64,600","64,900"
7906,20120501,000720,현대건설 (000720),102000,buy,"허문욱,이경신",KB증권,281842,"71,200","71,400"
8831,20120501,103140,풍산 (103140),42000,buy,김민수,삼성증권,281933,"28,900","30,100"
9586,20120428,000660,SK하이닉스 (000660),39000,buy,"진성혜,이현희",현대증권,281634,"27,400","28,050"
13106,20181231,108490,로보티즈(108490)서비스용 로봇 산업의 고성장 수혜,0,sell,김재훈,미래에셋대우,506957,"16,600","17,200"
13160,20181231,215100,로보로보(215100)세계로 도약이 기대되는 교육용 로봇 업체,0,sell,"김두현,이정기",하나금융투자,506928,"1,870","1,920"
13876,20161230,205100,엑셈(205100),0,sell,이성빈,교보증권,404018,"3,365","3,505"
14927,20170430,014790,한라(014790)현금이 들어오고 투자가 시작된다!,0,sell,라진성,키움증권,423527,"4,545","4,530"
14930,20181231,263810,상신전자(263810)긍정적인 주주환원 정책,0,sell,박원재,미래에셋대우,506951,"5,670","5,800"
15352,20170430,011780,금호석유(011780)티끌 모아 태산,80000,neutral,윤성노,대신증권,423565,"75,400","76,100"
15488,20161230,128940,한미약품(128940),450000,neutral,"서근희,정다은",대신증권,404022,"308,500","305,500"
15739,20120428,052690,한전기술 (052690),80000,neutral,"신민석,홍진주",신한금융,281667,"69,900","66,900"
15819,20120428,011200,현대상선 (011200),32000,neutral,"신민석,홍진주",신한금융,281665,"28,300","28,300"
17137,20170430,000100,유한양행(000100)1Q17 Review,275000,neutral,신재훈,이베스트증권,423616,"233,500","232,000"
17166,20170430,037560,CJ헬로비전(037560)1Q17 Review,9000,neutral,김현용,이베스트증권,423611,"9,730","9,430"
18636,20120428,035760,CJ오쇼핑(035760),240000,neutral,"이상구,태윤선",현대증권,281633,"183,200","179,500"
19962,20120428,051600,한전 KPS (051600),40000,neutral,"신민석,홍진주",신한금융,281668,"40,550","40,850"
19993,20120501,043650,국순당(043650),8500,neutral,"유 진,한지훈",현대증권,281929,"8,330","8,140"
21119,20120501,035720,다음 (035720),200000,strongbuy,김진구,NH증권,281944,"109,900","106,000"
21121,20120501,005940,우리투자증권 (005940),13000,strongbuy,박석현,한화증권,281887,"11,400","11,200"

In [334]:
df = pd.read_csv('./csv/sampled_df_price21260_add.csv', index_col=0)

In [337]:
# 이제 nan값 997-29 = 968개 남아야 함
df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,20180418,88350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,20160523,92070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,20140729,270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,20190403,35720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,20160912,20560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...
21256,20111114,830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705,NaN,NaN
21257,20111111,97230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
21258,20111110,210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
21259,20111107,10620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"
21260,20111104,33630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201,NaN,NaN

In [338]:
df = df.combine_first(nan_df_29)

In [342]:
df[df.isnull().any(1)].to_csv('nan_df_968.csv', encoding='utf-8-sig')

In [348]:
df_1=df.dropna()

In [350]:
df_1.to_csv('./csv/sampled_df_price20293_sub.csv', encoding='utf-8-sig')

In [142]:
df = pd.read_csv('sampled_df_price20293_sub.csv', dtype={'code':str, '작성일':str})

In [143]:
df['code'] = df['code'].apply(lambda x: x.zfill(6))

In [66]:
import exchange_calendars as ecals

XKRX = ecals.get_calendar("XKRX") 
print(XKRX.is_session("20210922")) 
print(XKRX.previous_open(pd.Timestamp('20210922')))

False
2021-09-17 00:00:00+00:00

In [144]:
df

,Unnamed: 0,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,0,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,1,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,2,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,3,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,4,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...,...
20288,21253,20111114,010950,S-Oil(010950),151000,strongbuy,손영주,교보증권,272774,"121,500","122,500"
20289,21254,20111114,028050,삼성엔지니어링 (028050),321000,strongbuy,조주형,교보증권,272741,"235,000","236,500"
20290,21257,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
20291,21258,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
20292,21259,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"

In [145]:
df.insert(2, '개장일', df['작성일'])

In [146]:
df

,Unnamed: 0,작성일,개장일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
0,0,20180418,20180418,088350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108,"6,160","6,160"
1,1,20160523,20160523,092070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646,"12,600","12,450"
2,2,20140729,20140729,000270,기아차(000270),77000,buy,이윤석,SK증권,329427,"57,700","60,500"
3,3,20190403,20190403,035720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412,"103,000","102,500"
4,4,20160912,20160912,020560,아시아나항공(020560),5300,buy,정유석,교보증권,391416,"4,850","4,600"
...,...,...,...,...,...,...,...,...,...,...,...,...
20288,21253,20111114,20111114,010950,S-Oil(010950),151000,strongbuy,손영주,교보증권,272774,"121,500","122,500"
20289,21254,20111114,20111114,028050,삼성엔지니어링 (028050),321000,strongbuy,조주형,교보증권,272741,"235,000","236,500"
20290,21257,20111111,20111111,097230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587,"20,000","19,000"
20291,21258,20111110,20111110,000210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570,"91,500","91,800"
20292,21259,20111107,20111107,010620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294,"117,500","117,000"

In [172]:
for i, dates in enumerate(df['개장일']):
    if not XKRX.is_session(dates):
        df['개장일'].loc[i] = ''.join(str(XKRX.previous_open(pd.Timestamp(dates)))[:10].split('-'))

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [177]:
df[df['Unnamed: 0'] == 1897]

,Unnamed: 0,작성일,개장일,code,제목,목표주가,투자의견,작성자,제공출처,idx,시가,종가
1801,1897,20170430,20170428,161390,한국타이어(161390)불황기에 잘한 회사가 호황기에 더 잘한다,77000,buy,"김진우,박성준",한국투자증권,423555,"59,300","58,900"

In [184]:
df.to_csv('sampled_df_price20293_sub_mod2.csv', encoding='utf-8-sig')

In [192]:
df = pd.read_csv('sampled_df_price20293_sub_mod2.csv', index_col=0)

In [194]:
df.loc[1897]

작성일                                20170430
개장일                                20170428
code                                 161390
제목      한국타이어(161390)불황기에 잘한 회사가 호황기에 더 잘한다
목표주가                                  77000
투자의견                                    buy
작성자                                 김진우,박성준
제공출처                                 한국투자증권
idx                                  423555
시가                                   59,300
종가                                   58,900
Name: 1897, dtype: object

In [191]:
df.to_csv('sampled_df_price20293_sub_mod2.csv', encoding='utf-8-sig')

In [215]:
df = pd.read_csv('standard_df.csv', index_col=0)

In [216]:
df

,작성일,개장일,Market,Name,code,Sector,목표주가,시가,종가,투자의견,작성자,제공출처,idx
0,20180418,20180418,KOSPI,한화생명,88350,보험업,11000,"6,160","6,160",buy,박혜진,이베스트증권,473108
1,20180531,20180531,KOSPI,한화생명,88350,보험업,9300,"5,740","5,570",buy,성용훈,한화투자증권,479661
2,20180918,20180918,KOSPI,한화생명,88350,보험업,6000,"4,880","4,860",buy,김지영,교보증권,493832
3,20210219,20210219,KOSPI,한화생명,88350,보험업,3500,"3,120","3,230",buy,정태준,유안타증권,583203
4,20121109,20121109,KOSPI,한화생명,88350,보험업,9000,"7,410","7,330",buy,이치영,이트레이드증권,293653
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20288,20150317,20150317,KOSPI,사조산업,7160,어로 어업,160000,"79,600","78,500",strongbuy,김승,SK증권,345498
20289,20150612,20150612,KOSPI,까뮤이앤씨,13700,건물 건설업,24000,"12,450","12,350",strongbuy,"이태경,한기현",현대증권,353325
20290,20150601,20150601,KOSDAQ,서전기전,189860,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업",24000,"12,850","13,350",strongbuy,이상우,유진투자증권,352285
20291,20150317,20150317,KOSDAQ,서전기전,189860,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업",24000,"13,500","14,150",strongbuy,이상우,유진투자증권,345568
20292,20140714,20140714,KOSDAQ,협진,138360,기타 화학제품 제조업,25200,"16,100","16,100",strongbuy,최소은,이트레이드증권,328374

In [295]:
df = pd.read_csv('standard_df1.csv', index_col=0)

In [296]:
df

,작성일,개장일,Market,Name,code,Sector,목표주가,시가,종가,투자의견,작성자,제공출처,idx,6month,1year
0,2018-04-18,2018-04-18,KOSPI,한화생명,88350,보험업,11000,"6,160","6,160",buy,박혜진,이베스트증권,473108,2018-10-15,2019-04-18
1,2018-05-31,2018-05-31,KOSPI,한화생명,88350,보험업,9300,"5,740","5,570",buy,성용훈,한화투자증권,479661,2018-11-27,2019-05-31
2,2018-09-18,2018-09-18,KOSPI,한화생명,88350,보험업,6000,"4,880","4,860",buy,김지영,교보증권,493832,2019-03-17,2019-09-18
3,2021-02-19,2021-02-19,KOSPI,한화생명,88350,보험업,3500,"3,120","3,230",buy,정태준,유안타증권,583203,2021-08-18,2022-02-19
4,2012-11-09,2012-11-09,KOSPI,한화생명,88350,보험업,9000,"7,410","7,330",buy,이치영,이트레이드증권,293653,2013-05-08,2013-11-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20288,2015-03-17,2015-03-17,KOSPI,사조산업,7160,어로 어업,160000,"79,600","78,500",strongbuy,김승,SK증권,345498,2015-09-13,2016-03-16
20289,2015-06-12,2015-06-12,KOSPI,까뮤이앤씨,13700,건물 건설업,24000,"12,450","12,350",strongbuy,"이태경,한기현",현대증권,353325,2015-12-09,2016-06-11
20290,2015-06-01,2015-06-01,KOSDAQ,서전기전,189860,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업",24000,"12,850","13,350",strongbuy,이상우,유진투자증권,352285,2015-11-28,2016-05-31
20291,2015-03-17,2015-03-17,KOSDAQ,서전기전,189860,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업",24000,"13,500","14,150",strongbuy,이상우,유진투자증권,345568,2015-09-13,2016-03-16
20292,2014-07-14,2014-07-14,KOSDAQ,협진,138360,기타 화학제품 제조업,25200,"16,100","16,100",strongbuy,최소은,이트레이드증권,328374,2015-01-10,2015-07-14

In [297]:
df.insert(14, '6month_개장일', df['6month'])

In [298]:
df.insert(16, '1year_개장일', df['1year'])

In [299]:
df

,작성일,개장일,Market,Name,code,Sector,목표주가,시가,종가,투자의견,작성자,제공출처,idx,6month,6month_개장일,1year,1year_개장일
0,2018-04-18,2018-04-18,KOSPI,한화생명,88350,보험업,11000,"6,160","6,160",buy,박혜진,이베스트증권,473108,2018-10-15,2018-10-15,2019-04-18,2019-04-18
1,2018-05-31,2018-05-31,KOSPI,한화생명,88350,보험업,9300,"5,740","5,570",buy,성용훈,한화투자증권,479661,2018-11-27,2018-11-27,2019-05-31,2019-05-31
2,2018-09-18,2018-09-18,KOSPI,한화생명,88350,보험업,6000,"4,880","4,860",buy,김지영,교보증권,493832,2019-03-17,2019-03-17,2019-09-18,2019-09-18
3,2021-02-19,2021-02-19,KOSPI,한화생명,88350,보험업,3500,"3,120","3,230",buy,정태준,유안타증권,583203,2021-08-18,2021-08-18,2022-02-19,2022-02-19
4,2012-11-09,2012-11-09,KOSPI,한화생명,88350,보험업,9000,"7,410","7,330",buy,이치영,이트레이드증권,293653,2013-05-08,2013-05-08,2013-11-09,2013-11-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20288,2015-03-17,2015-03-17,KOSPI,사조산업,7160,어로 어업,160000,"79,600","78,500",strongbuy,김승,SK증권,345498,2015-09-13,2015-09-13,2016-03-16,2016-03-16
20289,2015-06-12,2015-06-12,KOSPI,까뮤이앤씨,13700,건물 건설업,24000,"12,450","12,350",strongbuy,"이태경,한기현",현대증권,353325,2015-12-09,2015-12-09,2016-06-11,2016-06-11
20290,2015-06-01,2015-06-01,KOSDAQ,서전기전,189860,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업",24000,"12,850","13,350",strongbuy,이상우,유진투자증권,352285,2015-11-28,2015-11-28,2016-05-31,2016-05-31
20291,2015-03-17,2015-03-17,KOSDAQ,서전기전,189860,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업",24000,"13,500","14,150",strongbuy,이상우,유진투자증권,345568,2015-09-13,2015-09-13,2016-03-16,2016-03-16
20292,2014-07-14,2014-07-14,KOSDAQ,협진,138360,기타 화학제품 제조업,25200,"16,100","16,100",strongbuy,최소은,이트레이드증권,328374,2015-01-10,2015-01-10,2015-07-14,2015-07-14

In [300]:
for i, dates in enumerate(df['6month_개장일']):
    if not XKRX.is_session(dates):
        df['6month_개장일'].loc[i] = str(XKRX.previous_open(pd.Timestamp(dates)))[:10]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [301]:
for i, dates in enumerate(df['1year_개장일']):
    if not XKRX.is_session(dates):
        df['1year_개장일'].loc[i] = str(XKRX.previous_open(pd.Timestamp(dates)))[:10]

In [302]:
df.head(50)

,작성일,개장일,Market,Name,code,Sector,목표주가,시가,종가,투자의견,작성자,제공출처,idx,6month,6month_개장일,1year,1year_개장일
0,2018-04-18,2018-04-18,KOSPI,한화생명,88350,보험업,11000,"6,160","6,160",buy,박혜진,이베스트증권,473108,2018-10-15,2018-10-15,2019-04-18,2019-04-18
1,2018-05-31,2018-05-31,KOSPI,한화생명,88350,보험업,9300,"5,740","5,570",buy,성용훈,한화투자증권,479661,2018-11-27,2018-11-27,2019-05-31,2019-05-31
2,2018-09-18,2018-09-18,KOSPI,한화생명,88350,보험업,6000,"4,880","4,860",buy,김지영,교보증권,493832,2019-03-17,2019-03-15,2019-09-18,2019-09-18
3,2021-02-19,2021-02-19,KOSPI,한화생명,88350,보험업,3500,"3,120","3,230",buy,정태준,유안타증권,583203,2021-08-18,2021-08-18,2022-02-19,2022-02-18
4,2012-11-09,2012-11-09,KOSPI,한화생명,88350,보험업,9000,"7,410","7,330",buy,이치영,이트레이드증권,293653,2013-05-08,2013-05-08,2013-11-09,2013-11-08
5,2016-11-23,2016-11-23,KOSPI,한화생명,88350,보험업,8400,"6,580","6,780",buy,성용훈,한화투자증권,400398,2017-05-22,2017-05-22,2017-11-23,2017-11-23
6,2016-11-14,2016-11-14,KOSPI,한화생명,88350,보험업,9500,"6,340","6,390",buy,"김진상,정태준",HMC투자증권,398622,2017-05-13,2017-05-12,2017-11-14,2017-11-14
7,2012-03-20,2012-03-20,KOSPI,한화생명,88350,보험업,9100,"7,680","7,740",buy,배정현,SK증권,279289,2012-09-16,2012-09-14,2013-03-20,2013-03-20
8,2018-05-16,2018-05-16,KOSPI,한화생명,88350,보험업,9500,"6,020","5,970",buy,"김진상,정태준",현대차투자증권,477518,2018-11-12,2018-11-12,2019-05-16,2019-05-16
9,2013-08-09,2013-08-09,KOSPI,한화생명,88350,보험업,8600,"6,710","6,630",buy,정길원,대우증권,309260,2014-02-05,2014-02-05,2014-08-09,2014-08-08
10,2013-11-11,2013-11-11,KOSPI,한화생명,88350,보험업,8200,"6,630","6,640",buy,"송인찬,이관희",신한금융,314890,2014-05-10,2014-05-09,2014-11-11,2014-11-11
11,2016-05-12,2016-05-12,KOSPI,한화생명,88350,보험업,11000,"6,590","6,500",buy,박혜진,교보증권,379750,2016-11-08,2016-11-08,2017-05-12,2017-05-12
12,2016-12-12,2016-12-12,KOSPI,한화생명,88350,보험업,8000,"6,940","6,850",buy,박혜진,교보증권,402591,2017-06-10,2017-06-09,2017-12-12,2017-12-12
13,2017-01-18,2017-01-18,KOSPI,한화생명,88350,보험업,8500,"6,560","6,710",buy,"윤태호,김서연",한국투자증권,407011,2017-07-17,2017-07-17,2018-01-18,2018-01-18
14,2016-06-07,2016-06-07,KOSPI,한화생명,88350,보험업,8000,"6,370","6,410",buy,정준섭,유안타증권,381953,2016-12-04,2016-12-02,2017-06-07,2017-06-07
15,2015-02-16,2015-02-16,KOSPI,한화생명,88350,보험업,9200,"7,640","7,780",buy,이신영,HMC투자증권,343531,2015-08-15,2015-08-13,2016-02-16,2016-02-16
16,2017-02-27,2017-02-27,KOSPI,한화생명,88350,보험업,8000,"6,580","6,440",buy,박혜진,교보증권,413303,2017-08-26,2017-08-25,2018-02-27,2018-02-27
17,2013-02-07,2013-02-07,KOSPI,한화생명,88350,보험업,8500,"7,320","7,300",buy,서보익,유진증권,298747,2013-08-06,2013-08-06,2014-02-07,2014-02-07
18,2017-01-26,2017-01-26,KOSPI,한화생명,88350,보험업,8300,"6,470","6,360",buy,김지영,IBK투자증권,408380,2017-07-25,2017-07-25,2018-01-26,2018-01-26
19,2013-08-09,2013-08-09,KOSPI,한화생명,88350,보험업,8200,"6,710","6,630",buy,"송인찬,이관희",신한금융,309312,2014-02-05,2014-02-05,2014-08-09,2014-08-08
20,2011-11-09,2011-11-09,KOSPI,한화생명,88350,보험업,9900,"7,000","7,040",buy,김지현,하이증권,272466,2012-05-07,2012-05-07,2012-11-08,2012-11-08
21,2013-05-23,2013-05-23,KOSPI,한화생명,88350,보험업,9500,"6,940","6,900",buy,윤태호,한화증권,304807,2013-11-19,2013-11-19,2014-05-23,2014-05-23
22,2017-05-16,2017-05-16,KOSPI,한화생명,88350,보험업,8000,"6,630","6,660",buy,박혜진,교보증권,425979,2017-11-12,2017-11-10,2018-05-16,2018-05-16
23,2019-02-22,2019-02-22,KOSPI,한화생명,88350,보험업,0,"4,310","4,325",sell,"이남석,유승창",KB증권,514386,2019-08-21,2019-08-21,2020-02-22,2020-02-21
24,2019-01-14,2019-01-14,KOSPI,한화생명,88350,보험업,0,"4,220","4,195",sell,임희연,신한금융투자,508780,2019-07-13,2019-07-12,2020-01-14,2020-01-14
25,2017-04-12,2017-04-12,KOSPI,한화생명,88350,보험업,7300,"5,930","6,000",neutral,"장효선,이명준\t",삼성증권,420206,2017-10-09,2017-09-29,2018-04-12,2018-04-12
26,2017-01-02,2017-01-02,KOSPI,한화생명,88350,보험업,7000,"6,550","6,440",neutral,이남석,KTB투자증권,404078,2017-07-01,2017-06-30,2018-01-02,2018-01-02
27,2021-05-14,2021-05-14,KOSPI,한화생명,88350,보험업,4500,"4,215","3,950",neutral,박혜진,대신증권,589547,2021-11-10,2021-11-10,2022-05-14,2022-05-13
28,2013-02-07,2013-02-07,KOSPI,한화생명,88350,보험업,7700,"7,320","7,300",neutral,"장효선,민경완",삼성증권,298723,2013-08-06,2013-08-06,2014-02-07,2014-02-07
29,2012-02-08,2012-02-08,KOSPI,한화생명,88350,보험업,7000,"7,730","7,670",neutral,"장효선,민경완",삼성증권,277244,2012-08-06,2012-08-06,2013-02-07,2013-02-07
30,2019-05-15,2019-05-15,KOSPI,한화생명,88350,보험업,0,"3,615","3,600",neutral,"윤태호,차주영",한국투자증권,524684,2019-11-11,2019-11-11,2020-05-14,2020-05-14
31,2013-05-23,2013-05-23,KOSPI,한화생명,88350,보험업,7200,"6,940","6,900",neutral,"장효선,신동오",삼성증권,304799,2013-11-19,2013-11-19,2014-05-23,2014-05-23
32,2021-05-14,2021-05-14,KOSPI,한화생명,88350,보험업,4000,"4,215","3,950",neutral,이홍재,하나금융투자,589607,2021-11-10,2021-11-10,2022-05-14,2022-05-13
33,2020-02-24,2020-02-24,KOSPI,한화생명,88350,보험업,2400,"1,810","1,750",neutral,정태준,유안타증권,551884,2020-08-22,2020-08-21,2021-02-23,2021-02-23
34,2020-01-06,2020-01-06,KOSPI,한화생명,88350,보험업,2500,"2,275","2,240",neutral,강승건,하이투자증권,547560,2020-07-04,2020-07-03,2021-01-05,2021-01-05
35,2015-11-13,2015-11-13,KOSPI,한화생명,88350,보험업,9200,"8,000","8,130",neutral,원재웅,미래에셋증권,365978,2016-05-11,2016-05-11,2016-11-12,2016-11-11
36,2020-10-19,2020-10-19,KOSPI,한화생명,88350,보험업,1700,"1,515","1,570",neutral,김고은,메리츠종금증권,573332,2021-04-17,2021-04-16,2021-10-19,2021-10-19
37,2017-04-10,2017-04-10,KOSPI,한화생명,88350,보험업,8000,"5,980","5,940",neutral,강승건,대신증권,419593,2017-10-07,2017-09-29,2018-04-10,2018-04-10
38,2017-02-27,2017-02-27,KOSPI,한화생명,88350,보험업,7300,"6,580","6,440",neutral,"장효선,이명준",삼성증권,413390,2017-08-26,2017-08-25,2018-02-27,2018-02-27
39,2020-05-15,2020-05-15,KOSPI,한화생명,88350,보험업,0,"1,705","1,640",neutral,"장효선, 정민기",삼성증권,560455,2020-11-11,2020-11-11,2021-05-15,2021-05-14
40,2020-06-15,2020-06-15,KOSPI,한화생명,88350,보험업,2100,"1,490","1,400",neutral,정태준,유안타증권,563329,2020-12-12,2020-12-11,2021-06-15,2021-06-15
41,2013-10-17,2013-10-17,KOSPI,한화생명,88350,보험업,0,"6,950","7,100",neutral,이철호,한투증권,312942,2014-04-15,2014-04-15,2014-10-17,2014-10-17
42,2016-11-08,2016-11-08,KOSPI,한화생명,88350,보험업,0,"6,100","5,910",neutral,"윤태호,김서연",한국투자증권,397959,2017-05-07,2017-05-04,2017-11-08,2017-11-08
43,2020-11-16,2020-11-16,KOSPI,한화생명,88350,보험업,2100,"1,915","2,040",neutral,정태준,유안타증권,576017,2021-05-15,2021-05-14,2021-11-16,2021-11-16
44,2020-07-13,2020-07-13,KOSPI,한화생명,88350,보험업,2100,"1,415","1,425",neutral,정태준,유안타증권,565793,2021-01-09,2021-01-08,2021-07-13,2021-07-13
45,2013-11-11,2013-11-11,KOSPI,한화생명,88350,보험업,7200,"6,630","6,640",neutral,"장효선,신동오",삼성증권,314877,2014-05-10,2014-05-09,2014-11-11,2014-11-11
46,2020-05-15,2020-05-15,KOSPI,한화생명,88350,보험업,0,"1,705","1,640",neutral,박혜진,대신증권,560389,2020-11-11,2020-11-11,2021-05-15,2021-05-14
47,2014-05-15,2014-05-15,KOSPI,한화생명,88350,보험업,8300,"6,700","6,680",neutral,강승건,대신증권,325379,2014-11-11,2014-11-11,2015-05-15,2015-05-15
48,2014-11-13,2014-11-13,KOSPI,한화생명,88350,보험업,0,"8,430","8,490",neutral,"이태경,한기현",현대증권,336676,2015-05-12,2015-05-12,2015-11-13,2015-11-13
49,2021-01-29,2021-01-29,KOSPI,한화생명,88350,보험업,2500,"2,775","2,670",neutral,김고은,메리츠증권,581585,2021-07-28,2021-07-28,2022-01-29,2022-01-28

In [303]:
df.to_csv('standard_df_mod.csv', encoding='utf-8-sig')

In [307]:
df_1 = pd.read_csv('standard_df_mod.csv', index_col=0)

In [311]:
df_1[df_1.isnull().any(1)]

,작성일,개장일,Market,Name,code,Sector,목표주가,시가,종가,투자의견,작성자,제공출처,idx,6month,6month_개장일,1year,1year_개장일,close_6month,close_1year
3,2021-02-19,2021-02-19,KOSPI,한화생명,88350,보험업,3500,"3,120","3,230",buy,정태준,유안타증권,583203,2021-08-18,2021-08-18,2022-02-19,2022-02-18,3370.0,NaN
27,2021-05-14,2021-05-14,KOSPI,한화생명,88350,보험업,4500,"4,215","3,950",neutral,박혜진,대신증권,589547,2021-11-10,2021-11-10,2022-05-14,2022-05-13,3300.0,NaN
32,2021-05-14,2021-05-14,KOSPI,한화생명,88350,보험업,4000,"4,215","3,950",neutral,이홍재,하나금융투자,589607,2021-11-10,2021-11-10,2022-05-14,2022-05-13,3300.0,NaN
43,2020-11-16,2020-11-16,KOSPI,한화생명,88350,보험업,2100,"1,915","2,040",neutral,정태준,유안타증권,576017,2021-05-15,2021-05-14,2021-11-16,2021-11-16,3950.0,NaN
49,2021-01-29,2021-01-29,KOSPI,한화생명,88350,보험업,2500,"2,775","2,670",neutral,김고은,메리츠증권,581585,2021-07-28,2021-07-28,2022-01-29,2022-01-28,3430.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20239,2021-02-04,2021-02-04,KOSDAQ,이지바이오,353810,동물용 사료 및 조제식품 제조업,0,"6,740","6,650",sell,박찬솔,SK증권,582116,2021-08-03,2021-08-03,2022-02-04,2022-02-04,6900.0,NaN
20242,2021-02-02,2021-02-02,KOSDAQ,핑거,163730,소프트웨어 개발 및 공급업,0,"29,250","26,450",sell,박종선,유진투자증권,581926,2021-08-01,2021-07-30,2022-02-02,2022-01-28,23250.0,NaN
20249,2021-04-19,2021-04-19,KOSPI,교촌에프앤비,339770,음·식료품 및 담배 도매업,0,"20,700","20,800",sell,남성현,한화투자증권,587349,2021-10-16,2021-10-15,2022-04-19,2022-04-19,18450.0,NaN
20254,2021-07-07,2021-07-07,KOSDAQ,대원,7680,건물 건설업,0,"11,600","11,650",sell,신서정,SK증권,593415,2022-01-03,2022-01-03,2022-07-07,2022-07-07,NaN,NaN
20255,2021-02-15,2021-02-15,KOSPI,삼영화학,3720,플라스틱제품 제조업,0,"3,075","3,190",sell,이상현,하이투자증권,582906,2021-08-14,2021-08-13,2022-02-15,2022-02-15,3190.0,NaN

In [322]:
df_1['시가'].apply(lambda x: ''.join(x.split(',')))

0         6160
1         5740
2         4880
3         3120
4         7410
         ...
20288    79600
20289    12450
20290    12850
20291    13500
20292    16100
Name: 시가, Length: 20293, dtype: object

In [323]:
df_1['시가'].apply(lambda x: x.replace(',',''))

0         6160
1         5740
2         4880
3         3120
4         7410
         ...
20288    79600
20289    12450
20290    12850
20291    13500
20292    16100
Name: 시가, Length: 20293, dtype: object